### ISSUE TITLE
 org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [org.springframework.data.jpa.repository.query.AbstractJpaQuery$TupleConverter$TupleBackedMap] to type [com.example.entity.NewResult]]

### ISSUE THREAD

**Issue by sankalpbhatt** [spring-projects/spring-data-jpa#2649] opened 2022-09-30 15:43 UTC
Hi Team,

I am working on spring boot in Kotlin. I tried to create a custom query by joining tables. Needed a custom Entity class so created one.

Application starts but when I hit the query I get below error :
 _org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [org.springframework.data.jpa.repository.query.AbstractJpaQuery$TupleConverter$TupleBackedMap] to type [com.example.entity.NewResult]]_

My Entity Class looks like:
```kotlin
data class NewResult(
    val sectionCode: String,
    val sectionDescription: String,
)
```

My repository class:
```kotlin
interface NewRepository: JpaRepository<SomeClass, UUID> {

    @Query(nativeQuery = true, value = """
        select 
            f.section_code as sectionCode, 
            m.section_description as sectionDescription
            from table1 f
                join table2 m on m.code_id = f.id
    """)
    fun search(): List<NewResult>
}
```

Please let me know if this is a bug in JPA

**Comment by ngocluat** [comment] 2022-10-24 15:11
hi

**Comment by jamesdh** [comment] 2022-12-09 20:44
Duplicate of #2008?

**Comment by gregturn** [comment] 2023-04-28 16:38
I believe the problem is attempting to mix native queries with projections. 

This situation appears too complicated for `QueryUtils` to handle, and we aren't likely to approve a change there that would meet your needs. Your best best moving forward may be to implement a custom implementation. Check out https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.custom-implementations for more details on how to hook such a solution into your repository.

**Closed** 2023-04-28 16:39 UTC
Labels: status: waiting-for-triage, status: duplicate
