### ISSUE TITLE
Spring circular reference checking breaks custom spring data repos

### ISSUE THREAD

**Issue by symposion** [spring-projects/spring-data-jpa#2442] opened 2022-02-15 16:17 UTC
It's a common requirement to be able to inject the main repository interface into the implementation class of a custom repository interface. It requires a bit of care with the class naming but it has always worked fine. See e.g. this SO answer: https://stackoverflow.com/a/52892536

Since upgrading from Spring Boot 2.5.7 to 2.6.3, the latest circular reference checking in Spring complains that this is a circular reference (which it kind of is), and the only way to get the app to boot up is to turn off the circular reference checking entirely. It seems like there should be some sort of exception/special case for this Spring Data use case. Apologies if this ought to be raised against spring core/framework, it's not clear to me where this needs to be fixed.

**Comment by mp911de** [comment] 2022-02-21 15:11
This is a duplicate of https://github.com/spring-projects/spring-data-commons/issues/2319.

**Closed by mp911de** 2022-02-21 15:11 UTC
Labels: status: waiting-for-triage
