### ISSUE TITLE
Search Functionality in Docs Does Not Work

### ISSUE THREAD

**Issue by aonurozcan** [spring-projects/spring-data-jpa#3503] opened 2024-06-10 16:03 UTC
Hi,

Search functionaliy doesn't work in docs.

![image](https://github.com/spring-projects/spring-data-jpa/assets/7273908/025312ca-c523-4f07-9c35-c67294871978)
![image](https://github.com/spring-projects/spring-data-jpa/assets/7273908/75100bfc-4177-43f1-ad16-d9e5603876ab)

**Comment by mp911de** [comment] 2024-06-11 06:49
Duplicate of https://github.com/spring-projects/spring-data-build/issues/2310

**Closed by mp911de** 2024-06-11 06:49 UTC
Labels: status: waiting-for-triage
