### ISSUE TITLE
PUT not working for PagingAndSortingRepository - PATCH working

### ISSUE THREAD

**Issue by mikebski** [spring-projects/spring-data-jpa#2203] opened 2021-04-21 00:11 UTC
```kotlin
@RepositoryRestResource(collectionResourceRel = "task", path = "task")
interface TaskRepository : PagingAndSortingRepository<Task, Int>

@Entity
data class Tag(
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    val id: Int?,
    val tag: String
)
```

I set the content-type to application/json for all rquests

Now, when I POST to localhost:8080/tag with JSON data '{"tag": "test"}' it works fine (using postman and curl)

When I PATCH with JSON data '{"tag": "test2"}' to localhost:8080/tag/1 it updates the entity (when I do a get on localhost:8080/tag/1 it's updated)

When I PUT with JSON data '{"tag": "test3"}' to localhost:8080/tag/1 it DOES NOT UPDATE the entity (when I do a get on localhost:8080/tag/1 it's NOT updated). It returns 200 OK and there are no errors on the console.

My application.properties is empty and I'm using H2

Here's my build.gradle.kts:

```
 import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("org.springframework.boot") version "2.4.4"
    id("io.spring.dependency-management") version "1.0.11.RELEASE"
    kotlin("jvm") version "1.4.31"
    kotlin("plugin.spring") version "1.4.31"
    kotlin("plugin.jpa") version "1.4.31"
}

group = "com.saisols"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8

repositories {
    mavenCentral()
    jcenter()
    maven( url = "https://jitpack.io" )
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-data-rest")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	implementation("io.springfox:springfox-boot-starter:3.0.0")
	implementation("io.springfox:springfox-swagger-ui:3.0.0")
    implementation("com.github.ntrrgc:ts-generator:1.1.1")
    runtimeOnly("com.h2database:h2")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict")
        jvmTarget = "1.8"
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}
```

What gives?

**Comment by mp911de** [comment] 2021-04-26 14:58
Can you provide a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem so that we can consider all specifics? Kotlin arrangements tend to magically just works when some quirks are omitted which bears the risk that if we try to reproduce the issue it will just work.

**Comment by spring-projects-issues** [comment] 2021-05-03 15:02
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-05-10 15:02
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-05-10 15:02 UTC
Labels: status: feedback-reminder, status: waiting-for-triage
