### ISSUE TITLE
Users providing `@EnableJpaRepositories` break my library

### ISSUE THREAD

**Issue by rubasace** [spring-projects/spring-data-jpa#2266] opened 2021-07-18 12:24 UTC
This issue is relatively similar to the one described in [this old thread](https://github.com/spring-projects/spring-boot/issues/8134).

I have a common library that provides some extra functionality on top of Spring Data. It all works transparently and out-of-the-box, with users writing only normal Spring code; The library registers some entities and their repositories automatically with no further configuration from the user.

My problem comes when users want to use `@EnableJpaRepositories` annotation explicitly for any customization reason. According to the above-mentioned thread, I should be able to manually register  extra Spring Boot base packages and Spring Data should respect them. I'm doing it like this:

```java
public class CustomBeanDefinitionRegistryPostProcessor implements BeanDefinitionRegistryPostProcessor, PriorityOrdered {
    
    public void postProcessBeanDefinitionRegistry(BeanDefinitionRegistry beanDefinitionRegistry) throws BeansException {
        AutoConfigurationPackages.register(beanDefinitionRegistry, new String[]{"com.my.library.base.package"});
    }

    public int getOrder() {
        return Ordered.HIGHEST_PRIORITY;
    }

    public void postProcessBeanFactory(ConfigurableListableBeanFactory configurableListableBeanFactory) throws BeansException {
    }
}
```

I've even tried to register manually the above class using an `ApplicationListener<ApplicationContextInitializedEvent>`, setting it as the first factory postprocessor, so it was the absolute first thing being called in `PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors()`.  Yet, my approach only seems to work while users don't provide their own `@EnableJpaRepositories` annotation as part of the application. When they do, they are forced to also add my internal packages as well as theirs. Otherwise, my entities don't get scanned and my repositories don't get create, breaking the startup of the applications. 

Based on what's been discussed in the other issue, my assumption is that my approach should work. Is this a bug or still the desired behaviour? And, in the case of the latter, would it be possible to have any mechanism to register these extra paths for Spring Data regardless of what the user does with `@EnableJpaRepositories`. It might not seem that critical from the outside, but it's kind of bad having to couple customers applications code to our internal package structures.

**Comment by schauder** [comment] 2021-07-19 08:26
I think you are misreading the comments. 
Autoconfiguration backs off once it encounters manual configuration. 
This is by design. 

In the last comment to the referenced ticket Oliver Drotbohm recommends and links to an example using `@EntityScan`

**Comment by rubasace** [comment] 2021-07-20 17:56
I've developed a library similar to Spring Data REST that autogenerates CRUD endpoints controlling access to entities via granular RBAC. 

On one hand, it autogenerates everything for the entities the application provides (flagged with a marker annotation). On the other hand, it also provides some predefined entities for the RBAC related entities (user, role, authority) and some extra things for dealing with stuff like auditing.

In order for my library to properly work, I need to do two small changes to Spring Data JPA. First, I have to make the application scan also the packages where my entities live. I'm currently achieving this using `AutoConfigurationPackages`. Then, I also have to replace the default repository implementation with a custom one that extends `SimpleJpaRepository` functionality to offer a DSL for searching using `CriteriaBuilder`, retrieving the auditing information for the entities and their entries, etc. (I've also opened [this issue](https://github.com/spring-projects/spring-data-commons/issues/2417) asking for an easier way of doing that.

Out-of-the-box my library just behaves as expected from the application point of view. My main concern is that, if the users provide `@EnableJpaRepositories`, they have to be aware of my internal package structure and add the base package to the scanned ones. 

I think my use case is similar to the one exposed on the old thread I mentioned on the description of this issue: users of our libraries might want to tweak certain JPA parameters, but they will never want to stop using the entities we are providing, as they are core to the functionality our libraries are providing.

While I get the idea of not exposing these internal APIs, I still think it would be a nice balance if some properties were offered to configure this stuff (both the "extra" base packages and the base implementation classes); If provided via autoconfigurations, users would still benefit from this behaviour out-of-the-box, even if they want to fine-tune the JPA part. And they can always opt-out by disabling the autoconfiguration if they really know what they are doing.

**Comment by mp911de** [comment] 2021-07-21 07:45
> Then, I also have to replace the default repository implementation with a custom one that extends SimpleJpaRepository functionality to offer a DSL for searching using CriteriaBuilder, retrieving the auditing information for the entities and their entries, etc. (I've also opened this issue asking for an easier way of doing that.

The bean type you want to introspect is `JpaRepositoryFactoryBean`. Each use of `@Enable…Repositories` is followed by a set of repository factory bean registrations (`RepositoryFactoryBeanSupport`). You can inspect these beans (note that these could be also implementations of other Spring Data modules) for their `repositoryBaseClass` property. There's no getter for the property and we do not intend to expose it. You can use either a `BeanFactoryPostProcessor` to inspect the individual `BeanDefinition`s or a `BeanPostProcessor` if you want to operate on the level of the actual `JpaRepositoryFactoryBean`.

> Out-of-the-box my library just behaves as expected from the application point of view. My main concern is that, if the users provide @EnableJpaRepositories, they have to be aware of my internal package structure and add the base package to the scanned ones.

With coming up with your own `@Enable…Repositories` annotation you do not need to expose the internals of your library. By providing some infrastructure on top of `RepositoryConfigurationExtensionSupport` basically mirroring `JpaRepositoryConfigExtension` you can customize base packages (e.g. adopting `RepositoryConfigurationSource.getBasePackages()`). 

Note that Spring Boot's auto-config will back off once you register `JpaRepositoryFactoryBean` or a `JpaRepositoryConfigurationExtension` bean. If you want to leverage Boot's auto-configuration, then you need to provide similar functionality through other types resulting in potentially duplicating the factory bean and config extension.

See also https://github.com/spring-projects/spring-boot/blob/7e0fdb74f59334a8bf6d178157e907548607ff79/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/jpa/JpaRepositoriesAutoConfiguration.java#L77

I'm inclined to close this ticket since there's nothing we can do except for providing guidance.

**Comment by rubasace** [comment] 2021-07-21 08:54
> The bean type you want to introspect is JpaRepositoryFactoryBean.

I think that's what I'm currently doing:

```java
public class LibraryRepositoryFactoryBeanSupportPostProcessor implements BeanPostProcessor {

    private final LibraryBaseRepositoryRepositoryFactoryCustomizer customizer = new LibraryBaseRepositoryRepositoryFactoryCustomizer();
    private final Field repositoryBaseClassField;

    public LibraryRepositoryFactoryBeanSupportPostProcessor() {
        this.repositoryBaseClassField = ReflectionUtils.findField(RepositoryFactorySupport.class, "repositoryBaseClass");
        this.repositoryBaseClassField.setAccessible(true);
    }

    @Override
    public Object postProcessBeforeInitialization(Object bean, String beanName) throws BeansException {
        if (bean instanceof JpaRepositoryFactoryBean) {
            ((JpaRepositoryFactoryBean)bean).addRepositoryFactoryCustomizer(this.customizer);
        }

        return bean;
    }

    class LibraryBaseRepositoryRepositoryFactoryCustomizer implements RepositoryFactoryCustomizer {

        @Override
        public void customize(final RepositoryFactorySupport repositoryFactory) {
            Optional<Class<?>> repositoryBaseClass = (Optional<Class<?>>) ReflectionUtils.getField(repositoryBaseClassField, repositoryFactory);
            if(!repositoryBaseClass.isPresent()){
                repositoryFactory.setRepositoryBaseClass(BaseLibraryRepository.class);
            }
        }
    }
}
```

The part I'm not truly comfortable about is the reflection access to check if the repository has been set but I guess that's not something you would rename lightly.

Regarding the custom `@Enable...Repositories` approach, I think that's too complex for very little gain. I'm not sure if it would make more sense to do something similar to [Oliver's suggestion](https://github.com/spring-projects/spring-boot/issues/8134#issuecomment-553304291) and simply extend `@EnableJpaRepositories` adding an explicit import to a configuration that does the `@EntityScan` part, or something similar to that. The thing with Oliver's approach is that I don't really get how it works, cause when I provide `@EntityScan` from my autoconfigurations the application entities stop being processed.

**Comment by mp911de** [comment] 2021-07-21 12:32
That's why I mentioned `BeanFactoryPostProcessor` where you can introspect `PropertyValues` for `BeanDefinition`s that relate to `JpaRepositoryFactoryBean`.

The way how `@Enable…` annotations work is that they `@Import` a `ImportBeanDefinitionRegistrar` type that registers `BeanDefinition`s from its annotation. Check out `RepositoryBeanDefinitionRegistrarSupport` and `JpaRepositoriesRegistrar`.

Since there isn't anything left to do here. I'm closing this ticket.

**Closed by mp911de** 2021-07-21 12:32 UTC
Labels: status: feedback-provided, status: waiting-for-triage
