### ISSUE TITLE
uuid = bytea\n Hint: No operator matches the given name and argument types in spring boot 3

### ISSUE THREAD

**Issue by RoopaRJ** [spring-projects/spring-data-jpa#2731] opened 2022-12-14 17:24 UTC
Hi,

i have migrated from spring boot 2.7.5 to 3.0.0 , the java version we are using is 17,dialect i am using is org.hibernate.dialect.PostgreSQLDialect  after migration i am getting issue while saving records to db wherever uuid is present and the exception i am getting is uuid = bytea\n Hint: No operator matches the given name and argument types. You might need to add explicit type casts

the entity looks like:

```kotlin
@Entity
@Table(name = "abc", schema = "abcd")
data class ABCEntity(
        @Id
        @Column(name = "id")
        private var id: UUID,
}
```

Repository looks like:

```kotlin
@Repository
interface ABCEntityRepo : JpaRepository<ABCEntity, UUID>
```

column type in the db for id is uuid

**Error log:

```
org.hibernate.engine.jdbc.spi.SqlExceptionHelper","level":"ERROR","msg":"ERROR: operator does not exist: uuid = bytea\n  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.\n  Position: 175"}**
```

**Comment by schauder** [comment] 2022-12-15 08:31
This sounds very much like a Hibernate issue.

Please check if you get the same error when you use an `EntityManager` directly to persist the entity.
If so it is a Hibernate issue (assuming you use Hibernate as the JPA implementation).

If this is not the case we would need a full reproducer, including the database using Testcontainers.

**Comment by spring-projects-issues** [comment] 2023-01-16 15:32
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2023-01-23 15:32
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2023-01-23 15:32 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, status: feedback-reminder
