### ISSUE TITLE
Exception is thrown when saving entities using a composite key with long attribute

### ISSUE THREAD

**Issue by ThiesR** [spring-projects/spring-data-jpa#2357] opened 2021-11-15 09:08 UTC
When using a composite key in an entity class, that has a long attribute, the JpaRepository is throwing an exception when new entities are saved.

The id class
```
public class RateId {
  private long id;
  private LocalDate priceDate;

  // Getter, setter...
}
```

The entity class:
```
@Entity
@IdClass(RateId.class}
public class SecurityRate {
  
  @Id
  private long id;

  @Id
  private LocalDate priceDate;

  // other fields, getter, setter...
}
```

The repository:
```
@Repository
public interface SecurityRateRepo extends JpaRepository<SecurityRate, RateId> {
}
```

When calling `securityRateRepo.saveAll(listOfNewSecurityRates);` the following exception is thrown:
```
java.lang.NoSuchMethodException: long.<init>()
        at java.base/java.lang.Class.getConstructor0(Class.java:3349) ~[na:na]
        at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553) ~[na:na]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.AbstractNestablePropertyAccessor.<init>(AbstractNestablePropertyAccessor.java:131) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.beans.BeanWrapperImpl.<init>(BeanWrapperImpl.java:111) ~[spring-beans-5.3.8.jar!/:5.3.8]
        at org.springframework.data.util.DirectFieldAccessFallbackBeanWrapper.<init>(DirectFieldAccessFallbackBeanWrapper.java:40) ~[spring-data-commons-2.5.1.jar!/:2.5.1]
        at org.springframework.data.jpa.repository.support.JpaMetamodelEntityInformation$IdentifierDerivingDirectFieldAccessFallbackBeanWrapper.<init>(JpaMetamodelEntityInformation.java:341) ~[spring-data-jpa-2.5.1.jar!/:2.5.1]
        at org.springframework.data.jpa.repository.support.JpaMetamodelEntityInformation.getId(JpaMetamodelEntityInformation.java:165) ~[spring-data-jpa-2.5.1.jar!/:2.5.1]
        at org.springframework.data.repository.core.support.AbstractEntityInformation.isNew(AbstractEntityInformation.java:46) ~[spring-data-commons-2.5.1.jar!/:2.5.1]
        at org.springframework.data.jpa.repository.support.JpaMetamodelEntityInformation.isNew(JpaMetamodelEntityInformation.java:246) ~[spring-data-jpa-2.5.1.jar!/:2.5.1]
        at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:596) ~[spring-data-jpa-2.5.1.jar!/:2.5.1]
        at org.springframework.data.jpa.repository.support.SimpleJpaRepository.saveAll(SimpleJpaRepository.java:631) ~[spring-data-jpa-2.5.1.jar!/:2.5.1]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:289) ~[spring-data-commons-2.5.1.jar!/:2.5.1]
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137) ~[spring-data-commons-2.5.1.jar!/:2.5.1]
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121) ~[spring-data-commons-2.5.1.jar!/:2.5.1]
        at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:529) ~[spring-data-commons-2.5.1.jar!/:2.5.1]
        at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:285) ~[spring-data-commons-2.5.1.jar!/:2.5.1]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:599) ~[spring-data-commons-2.5.1.jar!/:2.5.1]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.8.jar!/:5.3.8]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:163) ~[spring-data-commons-2.5.1.jar!/:2.5.1]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:138) ~[spring-data-commons-2.5.1.jar!/:2.5.1]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.8.jar!/:5.3.8]
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80) ~[spring-data-commons-2.5.1.jar!/:2.5.1]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.8.jar!/:5.3.8]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.8.jar!/:5.3.8]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.8.jar!/:5.3.8]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.8.jar!/:5.3.8]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.8.jar!/:5.3.8]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.8.jar!/:5.3.8]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.8.jar!/:5.3.8]
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:174) ~[spring-data-jpa-2.5.1.jar!/:2.5.1]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.8.jar!/:5.3.8]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.8.jar!/:5.3.8]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.8.jar!/:5.3.8]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.8.jar!/:5.3.8]
```

**Comment by schauder** [comment] 2021-11-15 12:27
Please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

**Comment by ThiesR** [comment] 2021-11-16 10:03
I created an example for reproducing this error. It was actually harder than I thought, as error only occurred after I added the relation SecurityRate -> Security.

This is the link to the GitHub repo: [spring-data-jpa-composite-key](https://github.com/ThiesR/spring-data-jpa-composite-key)

**Comment by subes** [comment] 2021-12-17 20:49
Another Testcase that fails because of this. Somehow the same test is fine with Hibernate and EclipseLink. Only fails on Datanucleus: https://github.com/invesdwin/invesdwin-context-persistence/blob/master/invesdwin-context-persistence-parent/invesdwin-context-persistence-jpa-datanucleus/src/test/java/de/invesdwin/context/persistence/jpa/datanucleus/SimpleTestDaoTest.java

In this case it is not a composite, but a simple `java.lang.Long` id.

The error also occured with spring-data-jpa 2.5.6, 2.5.7, 2.6.0.
2.5.5 is the last version where this problem does not occur.

**Comment by gregturn** [comment] 2022-04-13 20:32
I crafted a much simpler test case, and don't see it failing. 

```java
public class RateId implements Serializable {

	private long id;
	private String customerId;

	public RateId() {}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getCustomerId() {
		return customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}
}
```

```java
@Entity
@IdClass(RateId.class)
public class SecurityRate {

	@Id
	@GeneratedValue(strategy = SEQUENCE) private long id;

	@Id private String customerId;

	public SecurityRate() {

		this.id = 0L;
		this.customerId = null;
	}

	public SecurityRate(String customerId) {

		this();
		this.customerId = customerId;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getCustomerId() {
		return customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}
}
```

```java
public interface SecurityRateRepository extends JpaRepository<SecurityRate, RateId> {}
```

```java
ExtendWith(SpringExtension.class)
@ContextConfiguration(classes = SampleConfig.class)
@Transactional
public class RepositoryWithCompositeScalarKeyTests {

	@Autowired SecurityRateRepository repository;

	@Test
	void storingCompositeKeyWithScalarLongWorks() {

		SecurityRate securityRate1 = new SecurityRate("customer-1");
		SecurityRate securityRate2 = new SecurityRate("customer-2");

		repository.saveAllAndFlush(List.of(securityRate1, securityRate2));

		List<SecurityRate> securityRates = repository.findAll();
		assertThat(securityRates).hasSize(2);
		assertThat(securityRates.get(0).getId()).isEqualTo(1L);
		assertThat(securityRates.get(0).getCustomerId()).isEqualTo("customer-1");
		assertThat(securityRates.get(1).getId()).isEqualTo(2L);
		assertThat(securityRates.get(1).getCustomerId()).isEqualTo("customer-2");
	}
}
```

...and it runs just fine. So something in the example you've created @ThiesR is introducing a variation I can't see. 

* You extend from a base entity
* You do NOT have a default constructor even though IdClasses are supposed to
* You also have other fragments pulled into the repository.

So I'm not quite sure which factor is causing this.

**Comment by spring-projects-issues** [comment] 2022-04-20 20:37
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-04-27 20:34
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-04-27 20:34 UTC
Labels: status: waiting-for-feedback, status: feedback-reminder
