### ISSUE TITLE
NamedGraph does not work with JoinColumn to non-identity column

### ISSUE THREAD

**Issue by thejeff77** [spring-projects/spring-data-jpa#2466] opened 2022-03-18 18:47 UTC
As soon as the annotation JoinColumn with referencedColumnName is set to a field that is a non-identity (@Id) column, the NamedGraph optimizations fail to work. 

`@JoinColumn(name = "myForeignKey", referencedColumnName = "secondaryId")`

Eg: https://stackoverflow.com/questions/71518885/namedentitygraph-doesnt-work-with-joincolumn

Thanks for any help/feedback

**Comment by schauder** [comment] 2022-03-22 09:18
This seems to be behaviour of the underlying JPA implementation.
I don't see how this is caused by Spring Data nor how it could or should be fixed by Spring Data.
Please create a ticket with Hibernate or whatever JPA implementation you are using.

If you disagree with this assessment please provide a reproducer that also demonstrates that the same problem does not occur when using the JPA implementation directly.

**Closed by schauder** 2022-03-22 09:18 UTC
Labels: status: waiting-for-triage
