### ISSUE TITLE
SimpleJpaRepository.delete(Specification<T> spec) throws NullPointerException [Kotlin]

### ISSUE THREAD

**Issue by ASaludo** [spring-projects/spring-data-jpa#3439] opened 2024-04-22 10:33 UTC
Hello,

I have a problem using JpaSpecificationExecutor.delete using a Specification Object

I'm using Kotlin and the @Nullable on top of the toPredicate function of Specification used line 477 with the null parameter of query seemed to be the problem 

`java.lang.NullPointerException: Parameter specified as non-null is null:
...
at org.springframework.data.jpa.repository.support.SimpleJpaRepository.delete(SimpleJpaRepository.java:477)`

**Comment by christophstrobl** [comment] 2024-04-22 11:01
Thanks for reporting. Care to give us a bit more context of what you're trying to archive?
I do see a potential nullability contract violation with `Specification#toPredicate` when no `CriteriaQuery` is  present due to `CriteriaBuilder#createCriteriaDelete(Class)` not implementing it.

**Comment by mp911de** [comment] 2024-04-25 08:54
That's a shortcoming of the Specification vs. Criteria Query design. Specifications have been designed for select queries and at some point, we enabled these for `delete` usage. We cannot provide a `CriteriaQuery` as `CriteriaDelete` isn't assignable into it. It's a duplicate of #3036.

At some point, we need to revisit our arrangement and find a path forward.

**Closed by mp911de** 2024-04-25 08:54 UTC
Labels: status: duplicate
