### ISSUE TITLE
Class-based DTOs are not yet supported.

### ISSUE THREAD

**Issue by anarchical** [spring-projects/spring-data-jpa#3702] opened 2024-12-04 14:43 UTC
springboot version: v3.3.7-SNAPSHOT

```
Page<SchoolInterface> pageResult = schoolRepository.findBy(specification, q -> q.as(SchoolInterface.class));
```
When projection target is Interface, it works well.

But error occurred when I change the projection target to DTOs(normal class or record type)

java.lang.UnsupportedOperationException: Class-based DTOs are not yet supported.

I hope to know why must use interface.

**Comment by christophstrobl** [comment] 2024-12-05 06:53
likely to be closed by #3654

**Comment by mp911de** [comment] 2024-12-06 10:10
Duplicate of #2327

**Closed by mp911de** 2024-12-06 10:10 UTC
Labels: status: duplicate
