### ISSUE TITLE
AssertionError (InvocationTargetException) when executing findBy query on Repository after upgrading from spring boot 3.1.1 to 3.1.2 (Hibernate dependency introduces assert statements, causing trouble)

### ISSUE THREAD

**Issue by stefanhendriks** [spring-projects/spring-data-jpa#3091] opened 2023-07-31 09:54 UTC
Not sure if this should be in spring-boot project, or hibernate or elsewhere. I chose this spot because I basically just updated a spring dependency and it is related to data accessing (and figured putting this issue in the spring-boot project would probably result into saying I should post it here anyway ;-) )

## Request
Please advice how to approach the following problem, as the introduced `assert` statement within hibernate causes unit tests to fail. I don't want to lock my Hibernate version, nor override it somewhere. I also want to be able to keep updating spring boot :)

## Short story
When upgrading Spring Boot to `3.1.1` to `3.1.2` my tests break. I get an `InvocationTarget` exception, which - upon investigation - turns out to be caused by an `assert` line coming from `Hibernate 6.2.6.Final`. 

When reverting back to Spring Boot 3.1.1, I see `Hibernate 6.2.5.Final` is used, which has no `assert` lines, and hence the code works (my tests are green). 

I can also 'fix' my problem by adding a `strict` version in my `build.gradle.kts` and excluding the new hibernate version from spring jpa-data, but thats not the way to go imo.

**Note**: The `assert` statement is introduced in Hibernate `6.2.6.Final` in `AbstractSqmPath` ~ line 61, in method `copyTo`. And it seems to break when resolving a join which I have on a view (atleast in my entity definition).

## Long(er) story

I have a project, written in Kotlin, using Gradle and Spring Boot and Hibernate.

Here a snippet of the `build.gradle.kts`:

```
version = System.getenv("REVISION") ?: "0.0.1"
java.sourceCompatibility = JavaVersion.VERSION_17

plugins {
    application
    jacoco
    id("org.springframework.boot") version "3.1.2" // <-- this breaks, using 3.1.1 works
    id("io.spring.dependency-management") version "1.1.2"
    id("org.sonarqube") version "4.3.0.3225"
    kotlin("jvm") version "1.9.0"
    kotlin("plugin.spring") version "1.9.0"
    kotlin("plugin.jpa") version "1.9.0"
}
```

When I change `org.springframework.boot` into version `3.1.1` my build works fine; once I upgrade to `3.1.2` I get an `InvocationTargetException` at a particular Repository that tries to query a view.

The Entity representing the view is called `ConnectionStatesViewByLastUpdatePerMonthEntityKey`:

```
@Embeddable
private class ConnectionStatesViewByLastUpdatePerMonthEntityKey(
    private val updatedMonth: Int,
    private val updatedYear: Int,
    private val bankbookInfo: BankbookInfoEntity,
) : Serializable

@Immutable
@IdClass(ConnectionStatesViewByLastUpdatePerMonthEntityKey::class)
@Entity(name = "ConnectionStatesViewByLastUpdatePerMonth")
class ConnectionStatesViewByLastUpdatePerMonthEntity(

    @Column
    @Id
    val updatedMonth: Int,

    @Column
    @Id
    val updatedYear: Int,

    @Id
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "BANKBOOK_INFO_FK")
    val bankbookInfo: BankbookInfoEntity,

    @Column
    val accountsCount: Byte,

) {
    override fun toString(): String {
        return "ConnectionStatesViewByLastUpdatePerMonthEntity(" +
            "updatedMonth=$updatedMonth, " +
            "updatedYear=$updatedYear, " +
            "accountsCount=$accountsCount, " +
            "bankbookInfo=${bankbookInfo.id}" +
            ")"
    }
}
```

The repository is as follows:
```
@Repository
interface ConnectionStatesViewByLastUpdatePerMonthRepository :
    ReadOnlyRepository<ConnectionStatesViewByLastUpdatePerMonthEntity, Long> {

    fun findByBankbookInfoIdAndUpdatedYearAndUpdatedMonth(
        bankbookUUID: UUID,
        year: Int,
        month: Int,
    ): ConnectionStatesViewByLastUpdatePerMonthEntity?

    fun findByUpdatedYearAndUpdatedMonth(year: Int, month: Int): List<ConnectionStatesViewByLastUpdatePerMonthEntity>
}
```

There is only one place where I use this repository, this code is calling the repository and breaks:
```
        val now = Instant.now(clock)

        val existingConnectionState =
            this.connectionStatesViewByLastUpdatePerMonthRepository.findByBankbookInfoIdAndUpdatedYearAndUpdatedMonth(
                bankbookInfo.id,
                now.year(),
                now.monthValue(),
            )
```

I have made sure all values are non-null (ie `bankbookInfo.id` is given, same goes for `now` and its values).

Running my accompanied unit test breaks:
<img width="998" alt="image" src="https://github.com/spring-projects/spring-data-jpa/assets/1332066/b5638bb3-f46f-44f6-91b1-8ed8c04cbf31">

When digging deeper:
<img width="1441" alt="image" src="https://github.com/spring-projects/spring-data-jpa/assets/1332066/a325dde1-eef9-4ea5-a891-f302d45faa87">

Looks like as if producing the query itself throws an Assertion error. When going to the first element in the stacktrace, I end up in `AbstractSqmPath`:

```
	protected void copyTo(AbstractSqmPath<T> target, SqmCopyContext context) {
		assert lhs == null || lhs.getNavigablePath() == target.getLhs().getNavigablePath()
				|| getRoot( lhs ).getNodeType() instanceof SqmPolymorphicRootDescriptor;
		super.copyTo( target, context );
		if ( reusablePaths != null ) {
			target.reusablePaths = new HashMap<>( reusablePaths.size() );
			for ( Map.Entry<String, SqmPath<?>> entry : reusablePaths.entrySet() ) {
				target.reusablePaths.put( entry.getKey(), entry.getValue().copy( context ) );
			}
		}
	}
```

Looks like the `assert` line seems to be thrown, not sure why this is a problem now and not before in 3.1.1.

Reverting back to 3.1.1 turns all my tests green again.

Did a bit more digging:

This `copyTo` is called often, it seems to break once it is trying to resolve the join:

<img width="1884" alt="image" src="https://github.com/spring-projects/spring-data-jpa/assets/1332066/da774d1b-28c8-4122-9bfd-173aee530587">

When reverting back to `3.1.1` (which works fine) I see the following result at the same point in trace:

(I did notice the same function in `3.1.1` does *not* have an assert statement, see:
```
	protected void copyTo(AbstractSqmPath<T> target, SqmCopyContext context) {
		super.copyTo( target, context );
		if ( reusablePaths != null ) {
			target.reusablePaths = new HashMap<>( reusablePaths.size() );
			for ( Map.Entry<String, SqmPath<?>> entry : reusablePaths.entrySet() ) {
				target.reusablePaths.put( entry.getKey(), entry.getValue().copy( context ) );
			}
		}
	}
```
)

I noticed this is the Hibernate implementation of version `6.2.5.Final`. There is no explicit version mentioned in the `build.kts` for hibernate, so this must be a transitive dependency. When running spring boot 3.1.2 I can see the transitive dependency of Hibernate becomes `6.2.6.Final`

Dependency tree using Spring boot 3.1.1:
<img width="529" alt="image" src="https://github.com/spring-projects/spring-data-jpa/assets/1332066/fedae00a-d9d7-47d4-b522-f6c4dd3da594">

And when using 3.1.2:
<img width="598" alt="image" src="https://github.com/spring-projects/spring-data-jpa/assets/1332066/5fbfd2e7-939e-4f08-8bf8-4bde2b63d97d">

**Comment by gregturn** [comment] 2023-07-31 19:24
Indeed, this likes like a duplicate of #3079, tracked via https://hibernate.atlassian.net/jira/core/projects/HHH/issues/HHH-16988

**Closed** 2023-07-31 19:24 UTC
Labels: status: duplicate

**Comment by stefanhendriks** [comment] 2023-08-01 07:12
missed the duplicate issue, thanks for pointing it out. Will await further fixes on Hibernate's side then 👍
