### ISSUE TITLE
incompatible data type in conversion in hsqldb when query IS NULL with java.sql.Timestamp with spring-data-jpa 2.6.2

### ISSUE THREAD

**Issue by daveyx** [spring-projects/spring-data-jpa#2486] opened 2022-04-13 02:14 UTC
referring to https://stackoverflow.com/questions/71836247/incompatible-data-type-in-conversion-in-hsqldb-when-query-is-null-with-java-sql

I don't know where to report this issue, so i start here.

it looks like hsqldb 2.5.2 is not compatible in this usecase with the provided hibernate version.

hsqldb version 2.5.2 dependency comes from spring-boot-starter-test.

however, shouldnt be there a testcase for stuff like that in spring-data-jpa ?

**Comment by schauder** [comment] 2022-04-13 07:43
At first glance this looks like an Hibernate or HSQLDB issue in which case the correct issue trackers would be https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues
or https://sourceforge.net/p/hsqldb/bugs/

If you think this is actually a Spring Data JPA issue, please provide an executable reproducer, preferable in form of a github repository.

**Comment by daveyx** [comment] 2022-04-18 23:54
thanks for answer

repo for reproduce is here:
https://github.com/daveyx/spring-data-hsqldb-timestamp-issue

in the meantime someone anserwerd here:
https://stackoverflow.com/questions/71836247/incompatible-data-type-in-conversion-in-hsqldb-when-query-is-null-with-java-sql/71902184#71902184

i think it is not a Spring Data JPA issue
hsqldb should not fail on NULL, so i probably will fire a report there.

but spring-starter-test updated the hsqldb version from hsqldb 2.5.1 to 2.5.2, making code fail.

Question:
shouldn't be there a testcase in spring-data-jpa, testing this in order to prevent the update of hsqldb if a behavior changes?

**Comment by schauder** [comment] 2022-04-19 06:56
Having a test for detecting any behaviour change would be awesome, but it is not feasible. Spring Data JPA builds on JPA and (mostly) only tests against different JPA implementations (Hibernate and EclipseLink) and even then we don't attempt to detect any possible behaviour change, but only those that we detect while trying to make a feature work against all implementations.

In deed a test against such a behaviour change as the one we are discussing here would only give a false sense of security since most people don't use HSQLDB in production, but any of hundreds of different combinations of database, driver and JPA implementation. 

I'm therefore going to close this issue. 

As a workaround downgrade HSQLDB 2.5.1

If you have a link to a HSQLDB issue for tracking this behaviour change please leave it in a comment.

**Closed by schauder** 2022-04-19 06:56 UTC
Labels: status: feedback-provided
