### ISSUE TITLE
QueryUtils.createCountQueryFor does not work for all sub queries

### ISSUE THREAD

**Issue by Artur-** [spring-projects/spring-data-jpa#2166] opened 2021-03-02 13:35 UTC
Given for instance
```
"SELECT NEW abc.ProductWithSales(product.name, product.price, product.category, (SELECT SUM(row.sum) FROM SaleRow row WHERE row.product = product.id)) FROM Product as product"
```

produces
```
select count(row) FROM SaleRow row WHERE row.product = product.id)) FROM Product as product
```

which is nonsense

**Comment by Artur-** [comment] 2021-03-02 13:36
A working count query for this case would be
```
"SELECT COUNT (product) FROM Product as product"
```

**Comment by Artur-** [comment] 2021-03-03 09:00
Another query would be the one mentioned in [Hibernate docs for sub queries](https://docs.jboss.org/hibernate/core/4.3/manual/en-US/html/ch16.html#queryhql-subqueries): 
```
select cat.id, (select max(kit.weight) from cat.kitten kit)
from Cat as cat
```

This is is handled incorrectly as well:
```
select count(kit) from cat.kitten kit) from Cat as cat
```

**Comment by schauder** [comment] 2021-03-03 10:05
The original scenario is a duplicate of #1895 I also consider the scenario mentioned in the previous comment the same issue.

**Closed by schauder** 2021-03-03 10:05 UTC
Labels: status: waiting-for-triage
