### ISSUE TITLE
DTO Projection not working with specification

### ISSUE THREAD

**Issue by nidhikaushal** [spring-projects/spring-data-jpa#2959] opened 2023-05-19 07:12 UTC
I was trying to use projection with specification, but I am getting the error: 
Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [com.entity.ParticipationEntity] to type [com.entity.TenantOnly]. The reason being select query has all the columns and not just the ones present in TenantOnly.

projection interface

```
public interface TenantOnly {
    String getTenantId();
}

@Data
@Entity
@Table(name = "participation", schema = "public")
public class ParticipationEntity {

    @Id
    @Column(name = "id")
    private Long id;

    @Column(name = "programId")
    private String programId;

    @Column(name = "tenantId")
    private String tenantId;

}
```

Spring Data repository

```
public interface ParticipationSpringDataRepository extends JpaRepository<ParticipationEntity, Long>, JpaSpecificationExecutor<ParticipationEntity> {
    List<TenantOnly> findAll(Specification specification);
}
```

    public List<String> getParticipatingTenants(List<String> tenantIds,  List<String> programIds, OffsetDateTime processedDate){
        List<TenantOnly> tenantOnlies = participationSpringDataRepository.findAll(
                Specification.where(tenantIdIn(tenantIds))
                        .and(programId(programIds)));

        return tenantOnlies.stream().map(tenantOnly -> tenantOnly.getTenantId()).toList();
    }

    private Specification<ParticipationEntity> tenantIdIn(List<String> tenantIds){
        return (root,  query, criteriaBuilder) -> {
            if(tenantIds == null || tenantIds.isEmpty()){
                return criteriaBuilder.conjunction();
            }
            return criteriaBuilder.in(root.get(ParticipationEntity_.TENANT_ID)).value(tenantIds);
        };
    }

build versions
org.springframework.boot:spring-boot-starter-data-jpa:3.0.5
org.postgresql:postgresql:42.6.0

**Comment by nidhikaushal** [comment] 2023-05-19 07:25
I have changed the repository invoking method to

```
public List<String> getParticipatingTenants(List<String> tenantIds,  List<String> programIds, OffsetDateTime processedDate){
    List<TenantOnly> tenantOnlies = participationSpringDataRepository.findAllDtoProjectedBy(
            Specification.where(tenantIdIn(tenantIds))
                    .and(programId(programIds)));

    return tenantOnlies.stream().map(tenantOnly -> tenantOnly.getTenantId()).toList();
}
```

and the repository interface to

```
public interface ParticipationSpringDataRepository extends JpaRepository<ParticipationEntity, Long>, JpaSpecificationExecutor<ParticipationEntity> {
    List<ParticipationDto> findAllDtoProjectedBy(Specification specification);
}
```

But it gives the following error now: 
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'participationSpringDataRepository' defined in com.entity.ParticipationSpringDataRepository defined in @EnableJpaRepositories declared on ParticipationApplication: Could not create query for public abstract java.util.List com.entity.ParticipationSpringDataRepository.findAllDtoProjectedBy(org.springframework.data.jpa.domain.Specification); Reason: Failed to create query for method public abstract java.util.List com.entity.ParticipationSpringDataRepository.findAllDtoProjectedBy(org.springframework.data.jpa.domain.Specification); At least 1 parameter(s) provided but only 0 parameter(s) present in query

**Comment by nidhikaushal** [comment] 2023-05-19 09:30
I tried invoking the repository using findBy: 

```
public List<String> getParticipatingTenants(List<String> tenantIds,  List<String> programIds, OffsetDateTime processedDate){
    List<TenantOnly> tenantOnlies = participationSpringDataRepository.findBy(Specification.where(tenantIdIn(tenantIds)),
                q -> q.as(TenantOnly.class).all());

    return tenantOnlies.stream().map(tenantOnly -> tenantOnly.getTenantId()).toList();
}
```

But the select query has all the columns. 
How do I select only the columns mentioned in projection and its distinct values?

**Comment by nidhikaushal** [comment] 2023-05-19 12:56
I looked at the classes FetchableFluentQueryByPredicate and FetchableFluentQueryBySpecification. Both of them add the properties in the hint and not the select part of the query, and the postgres driver probably is not honouring it.

**Comment by mp911de** [comment] 2023-07-13 12:53
Closing this as duplicate of #487

**Closed by mp911de** 2023-07-13 12:53 UTC
Labels: status: duplicate
