### ISSUE TITLE
Supported types is incorrect

### ISSUE THREAD

**Issue by xenoterracide** [spring-projects/spring-data-jpa#2659] opened 2022-10-06 21:36 UTC
This is incorrect, it would seem that `java.time.Instant` is also supported, sorry if this belongs in the commons repo. Note, I was trying to use OffsetDateTime for this.

```
  businessDivisionId=a
  createdOn=<null>
  id=0183ae78-9359-7422-a7b7-471f29af8980
  lastModifiedOn=<null>
  version=0
]; Supported types are [org.joda.time.DateTime, org.joda.time.LocalDateTime, java.util.Date, java.lang.Long, long]
```

**Comment by mp911de** [comment] 2022-10-07 07:09
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by spring-projects-issues** [comment] 2022-10-14 07:10
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by xenoterracide** [comment] 2022-10-17 16:37
hmm... maybe I opened this in the wrong repo? https://github.com/spring-projects/spring-data-commons/issues/880

**Comment by schauder** [comment] 2022-10-18 07:27
@xenoterracide Please provide a description that stands on its own. Referencing the issue where this was first discussed is fine and helpful, but nobody wants to hunt through a lengthy discussion to extract what exactly is requested.

**Comment by spring-projects-issues** [comment] 2022-10-25 07:30
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-11-01 07:30
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-11-01 07:30 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, status: feedback-reminder
