### ISSUE TITLE
Shared `EntityManager` is `synthetic`, preventing bean post processing

### ISSUE THREAD

**Issue by kzander91** [spring-projects/spring-data-jpa#2730] opened 2022-12-14 16:51 UTC
The `EntityManager` registered in `JpaRepositoryConfigExtension` is `synthetic` (which is new as of 3.0). Synthetic beans are not post-processed by Spring, in particular it is therefore no longer possible to apply AOP interceptors to it.

See https://github.com/spring-projects/spring-boot/issues/33510 and https://github.com/spring-projects/spring-data-jpa/commit/1bfc3595ce2e14cdc03decfe350f20e139e3c877#r82897830 for details.

**Comment by schauder** [comment] 2022-12-15 08:52
@christophstrobl Could you take a look? Especially at the referenced comment? That was on an AOT related change.

**Comment by christophstrobl** [comment] 2022-12-15 13:32
@schauder will, do. might take some time though.

**Comment by christophstrobl** [comment] 2022-12-15 14:50
I gave it a quick try without the `synthetic` flag wich seems to be fine also in AOT/native mode. But I need to do some further investigation. Changes are good this is a leftover that should have been removed. Things changed quite a bit since July. 
Thanks for reporting @kzander91 !

**Comment by quaff** [comment] 2023-01-29 01:00
Any update?

**Comment by quaff** [comment] 2023-02-20 06:51
@gregturn It's a regression block upgrading, could you resolve it ASAP?

**Comment by quaff** [comment] 2023-03-03 02:48
@christophstrobl Would you take a look?

**Comment by quaff** [comment] 2023-05-17 02:47
What's the decision?

**Comment by christophstrobl** [comment] 2023-06-09 07:50
Removing `entityManager.setSynthetic(true)` from `JpaRepositoryConfigExtension` worked for the aot/native smoke test.

**Comment by quaff** [comment] 2023-06-10 14:48
Then it's safe to merge https://github.com/spring-projects/spring-data-jpa/pull/2866.

**Comment by gregturn** [comment] 2023-06-14 21:11
Merged to `main`, backported to `3.1.x` and `3.0.x`.

**Closed by gregturn** 2023-06-14 21:11 UTC
Labels: type: regression, theme: aot
