### ISSUE TITLE
Incorrect pagination results while retrieving entities with one to many relation

### ISSUE THREAD

**Issue by SergiyDyrda** [spring-projects/spring-data-jpa#2794] opened 2023-02-10 15:30 UTC
Hi! Here is what I've got when moved from Spring Boot 2.7 to Spring Boot 3
Entity
```
@Entity
@Table(name = "users")
public class User {

    @Id @GeneratedValue(generator="system-uuid")
    @GenericGenerator(name="system-uuid", strategy = "uuid")
    private String id;

    @Column(name = "name")
    private String name;

    @Column(name = "attachments_ids")
    @ElementCollection(fetch = FetchType.LAZY)
    private List<String> attachmentsIds;
}
```
Repository
```
public interface UserRepository extends CrudRepository<User, String>,
        JpaRepository<User, String> {


    @EntityGraph(attributePaths = "attachmentsIds")
    Page<User> findAll(Pageable pageable);
}
```

Test
```
@Test
    void testPagination() {
       //save 10 users each of them has 3 attachments
        assertEquals(10, userRepository.findAll().size());

        PageRequest pageRequest = PageRequest.of(0, 8);
        Page<User> all = userRepository.findAll(pageRequest);
        assertEquals(8, all.getContent().size()); //fails. actual is 3
    }
```
Looks like query then uses left join to eagerly get attachments but sets limits for query 
```
select u1_0.id, a1_0.user_id, a1_0.attachments_ids, u1_0.name
from users u1_0
         left join user_attachments_ids a1_0 on u1_0.id = a1_0.user_id
offset 0 rows fetch first 8 rows only
```

I am still assuming that i've missed smth but 
1. Here is what i've found in Hibernate doc

**When limits or pagination are combined with a fetch join, Hibernate must retrieve all matching results from the database and apply the limit in memory!
This almost certainly isn’t the behavior you were hoping for, and in general will exhibit terrible performance characteristics.**

[Link](https://docs.jboss.org/hibernate/orm/6.1/userguide/html_single/Hibernate_User_Guide.html#hql-limit-offset)

2. With Spring Boot 2.7 fetch limits were not transmitted to SQL level

**Comment by SergiyDyrda** [comment] 2023-02-10 15:34
[test-project 2.zip](https://github.com/spring-projects/spring-data-jpa/files/10708937/test-project.2.zip)


Also attaching example app for reproduce

**Comment by mp911de** [comment] 2023-02-20 15:24
Closing as duplicate of #2744. `@EntityGraph` is specified as a query hint to (eagerly) load property paths. Changes that result in a different result multiplicity are a bug of the JPA provider.

**Closed by mp911de** 2023-02-20 15:24 UTC
Labels: status: waiting-for-triage
