### ISSUE TITLE
Return only specific columns when returning a collection of projections while using the JpaSpecificationExecutor#findBy

### ISSUE THREAD

**Issue by radarsh** [spring-projects/spring-data-jpa#3331] opened 2024-01-24 17:34 UTC
I would like to be able to return a collection of projections while using specifications to filter them. I found the newly introduced `findBy` convenience in the `JpaSpecificationExecutor` interface but when I try to return a page of projections, it simply ends up retrieving all the columns from the database. 

```java
// MyProjection is an interface with nothing special about it

// Here specification is dynamically constructed
return myRepository.findBy(specification, q -> q
            .as(MyProjection.class)
            .page(pageable));
```

This problem is very similar to the closed #2632. However, I cannot resort to using JPQL or native queries because I have a need to use complex and dynamically constructed specifications to filter out the results.

The table I am querying contains a few JSONB (Postgres) columns that can contain huge JSON documents. So, even though I'm declaring projection interfaces without the JSONB columns, the actual query being made to the database ends up still retrieving the unwanted columns. This causes a massive performance degradation and the approach doesn't scale well.

I'm really out of my depth here and would appreciate any insights or tips.

**Comment by quaff** [comment] 2024-01-25 03:55
It's a very useful feature. 

I have a naive idea to implement it but have two problems need to be resolved.
1. `ReturnedType::of` is not public
2. `ProjectionFactory` need injected by constructor

https://github.com/spring-projects/spring-data-jpa/blob/699d3a2e57e39dc50df67337dfe696de93a3dd4a/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/support/FetchableFluentQueryBySpecification.java#L103-L112

```java
		Collection<String> propertiesToUse = this.properties;
		ReturnedType returnedType = ReturnedType.of(resultType, entityType, projectionFactory);
		if (returnedType.isProjecting()) {
			propertiesToUse = returnedType.getInputProperties();
		}
		return new FetchableFluentQueryBySpecification<>(spec, entityType, resultType, sort, limit, propertiesToUse, finder,
				scroll, countOperation, existsOperation, entityManager);
```

**Comment by mp911de** [comment] 2024-01-26 10:59
Projection queries do not yet support tuple queries to constrain the selected fields. This is a duplicate of #3144.

**Closed by mp911de** 2024-01-26 10:59 UTC
Labels: status: waiting-for-triage
