### ISSUE TITLE
Useing Enums value in @Query

### ISSUE THREAD

**Issue by ryandong8321** [spring-projects/spring-data-jpa#2774] opened 2023-01-24 02:14 UTC
Hi team,

I have a @query to perform a update in multiple fields. The invoiceStatus field is an enum, which is stored as int in DB.

```
@Modifying
@Query("update OrderItemModel i set i.invoiceId = :invoiceId, i.invoiceStatus = 2"
            + " where i.referenceNumber in :refs")
    void itemsToInvoice(@Param(value = "invoiceId") String invoiceId,
                              @Param(value = "bookingRefs") List<String> refs);
```

It worked fine before we migrate spring boot to 3.0.0. Now I got the Exception as below

```
org.hibernate.query.SemanticException: The assignment expression type [java.lang.Integer] did not match the assignment path type [xxx.OrderItemModel$InvoiceStatus] for the path [i.invoiceStatus] [update OrderItemModel i set i.invoiceId = :invoiceId, i.invoiceStatus = 2 where i.referenceNumber in :bookingRefs]
```

Could any one please help me to check this issue?

Thanks.

**Comment by ryandong8321** [comment] 2023-01-31 03:11
Hi @quaff , thanks for your reply, but could you please explain it exactly for me or how can i fix it? Thanks again

**Comment by quaff** [comment] 2023-01-31 07:28
You can use `i.invoiceStatus = xxx.OrderItemModel.InvoiceStatus.XXX` instead of `i.invoiceStatus = 2`

**Comment by ryandong8321** [comment] 2023-02-01 03:26
Hi @quaff, Thanks for your reply. Yes, i did but it does not work 😭 .

**Comment by quaff** [comment] 2023-02-01 06:46
> Hi @quaff, Thanks for your reply. Yes, i did but it does not work 😭 .

Then `i.invoiceStatus = xxx.OrderItemModel$InvoiceStatus.XXX` should works since `InvoiceStatus` is inner class.

**Comment by quaff** [comment] 2023-02-01 06:47
> Hi @quaff, Thanks for your reply. Yes, i did but it does not work 😭 .

Then `i.invoiceStatus = xxx.OrderItemModel$InvoiceStatus.XXX` should works since `InvoiceStatus` is inner class.

**Comment by quaff** [comment] 2023-02-01 06:47
> Hi @quaff, Thanks for your reply. Yes, i did but it does not work 😭 .

Then `i.invoiceStatus = xxx.OrderItemModel$InvoiceStatus.XXX` should works since `InvoiceStatus` is inner class.

**Comment by ryandong8321** [comment] 2023-02-01 22:15
Hi @quaff, I will try it. Thanks

**Comment by chackomathew** [comment] 2023-02-20 13:39
I faced the same issue and had to add fully qualified name of the enum class. Is this an issue with Spring data JPA?

**Comment by schauder** [comment] 2023-02-20 13:48
This sounds very much like a Hibernate issue.
I recommend creating a reproducer based purely on Hibernate and submitting an issue with them.

If you think this is actually a Spring Data issue, please provide a reproducer for the issue including a test case that demonstrates the correct behaviour using the `EntityManager` directly.

**Comment by spring-projects-issues** [comment] 2023-02-27 13:52
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2023-03-06 13:53
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2023-03-06 13:53 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, status: feedback-reminder
