### ISSUE TITLE
Add Enable/disable option for Ignore case

### ISSUE THREAD

**Issue by mvishnumohan** [spring-projects/spring-data-jpa#2617] opened 2022-08-10 04:48 UTC
Methods like findByNameIgnoringCase is adding UPPER irrespective of db level configurations and not hitting the indexes. In the scenario, we are supporting mssql and postgres, where postgres needs UPPER in where clause to achieve IgnoreCase whereas MSSQL does not need it. The query will work but it will not hit / use the index on name. Mssql doesnot support functions in Index otherwise we could have add an index with UPPER(name).

**Comment by schauder** [comment] 2022-08-10 08:31
There was a similar issue reported a while ago. Not sure if it was for Spring Data JPA or JDBC. And can't find it anymore It was asking for making the function used (`lower` vs `upper`) configurable. We probably allow for three options: _lower_, _upper_, _none_

**Comment by schauder** [comment] 2022-08-29 14:25
We should also consider introducing a configuration object that can also hold the escape character.

**Comment by gregturn** [comment] 2022-09-20 18:46
https://github.com/spring-projects/spring-data-jpa/issues/2420 is the issue where we aligned ALL querying, be it JPA or Querydsl, to use the same modifier for `ignoresCase` suffixes. Since Querydsl was using `lower`, we ensure everything else did the same.

**Comment by OrangeDog** [comment] 2024-02-15 15:54
@gregturn that issue is where you _said_ you would do that. But the associated commits did not do that. It didn't add any tests to confirm it either.

**Comment by mp911de** [comment] 2024-11-22 09:50
Closing as duplicate of #2420

**Closed by mp911de** 2024-11-22 09:50 UTC
Labels: status: duplicate
