### ISSUE TITLE
Query by Example no longer works in Spring Data Commons 2.4.8, but worked in Spring Data Commons 2.3.6.RELEASE

### ISSUE THREAD

**Issue by pmihalcin** [spring-projects/spring-data-jpa#2210] opened 2021-04-29 09:39 UTC
New version of Spring Data broke Query By Example functionality.
This issue started occurring when I bumped Spring Boot to `2.4.5`, Spring Data Commons to `2.4.8` from Spring Boot `2.3.8.RELEASE` and Spring Data Commons `2.3.6.RELEASE`

Here is simple example which fails on:
```
org.springframework.dao.InvalidDataAccessApiUsageException: Target object must not be null; nested exception is java.lang.IllegalArgumentException: Target object must not be null

	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:374)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:235)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:551)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:174)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy398.findOne(Unknown Source)
	at org.springframework.data.repository.query.QueryByExampleExecutor$findOne.call(Unknown Source)
```

The code doesn't arrive in `org.springframework.data.jpa.repository.support.SimpleJpaRepository#findOne(org.springframework.data.domain.Example<S>)` and exception occurs somewhere in AOP

```
@Entity
public class Sms {

    private PhoneNumber phoneNumber;

    public Sms() {
    }
	
    @Embedded
    public PhoneNumber getPhoneNumber() {
        return phoneNumber;
    }

    private void setPhoneNumber(final PhoneNumber phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
}

@Embeddable
public final class PhoneNumber {

    private String value;

    public PhoneNumber(final String value) {
        this.value = value;
    }

    private PhoneNumber() {
    }

    @Column
    private String getValue() {
        return value;
    }

    private void setValue(final String value) {
        this.value = value;
    }
}
```

```
Example<Sms> example = Example.of(new Sms(phoneNumber: new PhoneNumber(123)))
Sms sms = smsRepository.findOne(example)
```

**Comment by schauder** [comment] 2021-05-03 09:27
Please provide a reproducer. We have tests for Query By Example so something has to be special about this use case. Without a reproducer this easily gets very difficult to hunt down.

**Comment by spring-projects-issues** [comment] 2021-05-10 09:27
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-05-17 09:32
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-05-17 09:32 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback
