### ISSUE TITLE
Spring data specification pageable NULLS_[FIRST/LAST] not working. 

### ISSUE THREAD

**Issue by alexis-puska** [spring-projects/spring-data-jpa#2128] opened 2020-12-30 14:58 UTC
Hi all, 
I have create a specification for querying my database, I would like to set the precedence of null ordering, I create a pageable with custom sort : 

Pageable customPageable = pageable;

        for (Order sort : pageable.getSort()) {
            if (sort.getProperty().equals("column")) {
                List<Sort.Order> orderList = new ArrayList<>();
                if (sort.isAscending()) {
                    orderList.add(new Sort.Order(Sort.Direction.ASC,
                            "column", NullHandling.NULLS_FIRST));
                } else {
                    orderList.add(new Sort.Order(Sort.Direction.DESC,
                            "column", NullHandling.NULLS_LAST));
                }
                customPageable = PageRequest.of(pageable.getPageNumber(), pageable.getPageSize(), Sort.by(orderList));
            }
        }

repository.findAll(new Specification(), customPageable);

And when the request is execute on postgres database, only ASC or DESC is readable inside the log file. 

i do it wrong, this is a missing functionnality or a bug ?

**Comment by schauder** [comment] 2021-01-04 06:42
This is a duplicate of https://github.com/spring-projects/spring-data-jpa/issues/1280 and caused by JPA not supporting specification of null precedence.

**Closed by schauder** 2021-01-04 06:42 UTC
Labels: status: waiting-for-triage
