### ISSUE TITLE
BadJpqlGrammarException no viable alternative at input for reserved keyword: cannot escape

### ISSUE THREAD

**Issue by multanis63** [spring-projects/spring-data-jpa#3056] opened 2023-07-07 08:58 UTC
Hello,

Since 3.1.1, the following entity / query is not working anymore:

```
@Entity
@Table
public class TestEntity {

    @Id
    @Column(name = "ID")
    private Long id;

    @NotNull
    @Column(name = "TEST_TYPE", nullable = false)
    private String type;
    }
}
```

```
@Query(value = "select te from TestEntity te where te.type = :type")
List<TestEntity> findByType(@Param("type") String type);
```

Result: org.springframework.data.jpa.repository.query.BadJpqlGrammarException: Line 1:34 no viable alternative at input 'te.type'; Bad JPQL grammar

Seems related to #2791 but I cannot make it work.
I'm not using Hibernate but eclipselink with h2.

What I've tried (all not working):
```
@Query(value = "select te from TestEntity te where te.`type` = :type")
List<TestEntity> findByType(@Param("type") String type);

@Query(value = "select te from TestEntity te where te.\"type\" = :type")
List<TestEntity> findByType(@Param("type") String type);

@Query(value = "select te from TestEntity te where te.type = :testType")
List<TestEntity> findByType(@Param("testType") String type);

@Query(value = "select te from TestEntity te where te.type2 = :type")
List<TestEntity> findByType(@Param("type") String type);
```

The only way to make it work is by renaming BOTH entity field and query param:
```
@Query(value = "select te from TestEntity te where te.type2 = :testType")
List<TestEntity> findByType(@Param("testType") String type);
```

Or to not use JPQL (but that's not the goal):
```
List<TestEntity> findByType(String type);
```

Thanks,

**Comment by gregturn** [comment] 2023-07-10 14:08
Possibly duplicate of https://github.com/spring-projects/spring-data-jpa/issues/3057

**Comment by gregturn** [comment] 2023-07-10 14:09
Possible duplicate of #3062

**Comment by gregturn** [comment] 2023-07-10 16:08
The fix was merged to `main` and backported to `3.1.x`.

**Closed by gregturn** 2023-07-10 16:08 UTC
Labels: status: duplicate

**Comment by SergeVolodin** [comment] 2024-06-05 06:32
@gregturn , Good Day.
 Recently we encountered a similar problem, but for the `lateral` keyword, when it is an entity field and need to build a jpql query.
 We encountered this issue while migrating from Spring Boot 3.0 to Spring Boot 3.1 (spring-data-jpa 3.1.*)
 
 Thanks.

**Comment by christophstrobl** [comment] 2024-06-05 06:48
@SergeVolodin thanks for raising awareness - I've created #3496 to tackle the issue.
