### ISSUE TITLE
Kotlin with Spring Boot 3 entity inheritance issue

### ISSUE THREAD

**Issue by jan-schumacher** [spring-projects/spring-data-jpa#2867] opened 2023-03-18 07:29 UTC
I found a some kind of weird behaviour with loading inherited entities.

I created an example project with one entity that extends another (with @Intehitance annotation) to prove the point. https://github.com/jan-schumacher/KotlinJpaInheritanceIssue

After loading the entity the overridden fields were not loaded correctly. They seem to be put inside the parent class instead of the child. In the debugger it looks like seen in the screenshot.
<img width="618" alt="Screenshot 2023-03-18 at 08 24 16" src="https://user-images.githubusercontent.com/9511748/226091520-c65e8ab9-1e37-4052-99f6-5a0ec075963f.png">
When loading result.value2 it's always null. 
I overloaded the getter of value1 to load `super.name` which works and proves the point but is obviously not a good solution.

When switching back and forth between Spring Boot 2.7.6 and Spring Boot 3.0.4 this implementation only works in 2.7.6

**Comment by christophstrobl** [comment] 2023-03-20 06:30
Sounds like spring-projects/spring-data-commons#1911.

**Comment by jan-schumacher** [comment] 2023-03-20 06:43
Shouldn't this be fixed than? As well, I don't get the `org.springframework.data.mapping.MappingException: Ambiguous field mapping detected`

**Comment by jan-schumacher** [comment] 2023-03-20 06:47
I will try this version

**Comment by jan-schumacher** [comment] 2023-03-20 07:02
The commit is tagged 3.1.0-M2 but doesn't seem to be included? @christophstrobl

**Comment by jan-schumacher** [comment] 2023-03-20 07:48
Anyway. I updated my example to spring-data-jpa/commons 3.1.0-M2 and still getting the same result

**Comment by schauder** [comment] 2023-03-20 08:49
This sounds very much like a Hibernate issue, since all the JPA mapping is done by it.
I recommend creating a reproducer based purely on Hibernate and submitting an issue with them.

If you think this is actually a Spring Data issue, please provide a reproducer for the issue including a test case that demonstrates the correct behaviour using the `EntityManager` directly.

**Comment by jan-schumacher** [comment] 2023-03-20 09:04
I updated the example project with a pure hibernate Test. I unwraped the SessionFactory from the EntitiyManagerFactory. Is this enough pure Hibernate?
https://github.com/jan-schumacher/KotlinJpaInheritanceIssue/blob/main/src/test/kotlin/com/example/kotlinjpainheritanceissue/HibernateImplementationTests.kt

With pure Hibernate it works as expected with inheritance.

**Comment by schauder** [comment] 2023-03-20 09:37
Thanks for the test. Yes, that seems to demonstrate that the problem is on our side.

**Comment by jan-schumacher** [comment] 2023-03-22 07:59
@schauder This topic didn't let me loose. 
So I tried to figure out where the problem lies and I found something that might prove that spring data is not broken.
I updated the HibernateImplementationTests class. 
https://github.com/jan-schumacher/KotlinJpaInheritanceIssue/blob/main/src/test/kotlin/com/example/kotlinjpainheritanceissue/HibernateImplementationTests.kt
And I created a regression test that uses only hibernate that proves the bug in hibernate.
https://github.com/jan-schumacher/KotlinJpaInheritanceIssue/blob/main/hibernate-orm-6/src/test/kotlin/bugs/JPAUnitTestCase.kt

**Comment by schauder** [comment] 2023-03-22 08:26
Thanks for the work on this. 
I don't have any leverage on the Hibernate team, but they are fixing Hibernate 6 bugs left and right.


Closing this issue as it is not a Spring Data problem.

**Closed** 2023-03-22 08:26 UTC
Labels: for: external-project, in: kotlin

**Comment by albertscholtz** [comment] 2024-04-10 14:02
This worked for me when changing all affected data class constructor fields to `var` types instead of `val`, and also setting the annotations to target getters using `get:` for example `@get@Column`.
