### ISSUE TITLE
@Query("delete from xxxxx") SQLGrammarException: could not execute statement

### ISSUE THREAD

**Issue by chenygs** [spring-projects/spring-data-jpa#3459] opened 2024-04-30 06:01 UTC
package com.medtion.core.domain;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonView;
import com.medtion.core.view.View;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import javax.persistence.*;

@Getter
@Setter
@Entity
@Table(name = "test_dict")
@JsonIgnoreProperties(value = {"hibernateLazyInitializer", "handler"})
public class TestDict {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    @JsonView(value = View.UserView.class)
    private Integer id;

    @Column(name = "name")
    @JsonView(value = View.UserView.class)
    private String name;

    @JoinColumn(name = "pid")
    @ManyToOne(fetch = FetchType.LAZY)
    @NotFound(action = NotFoundAction.IGNORE)
    private TestDict parent;

    @Column(name = "weight")
    @JsonView(value = View.UserView.class)
    private Integer weight;

    @JoinColumn(name = "group_id")
    @ManyToOne(fetch = FetchType.LAZY)
    @NotFound(action = NotFoundAction.IGNORE)
    @JsonView(value = View.UserView.class)
    private TestDictGroup group;

}

**Comment by christophstrobl** [comment] 2024-04-30 06:26
duplicate of #3458

**Closed by christophstrobl** 2024-04-30 06:26 UTC
Labels: status: waiting-for-triage
