### ISSUE TITLE
JPARepository does not use TypeDef definitions in Entity

### ISSUE THREAD

**Issue by stefanrybacki** [spring-projects/spring-data-jpa#2221] opened 2021-05-28 15:08 UTC
Spring Boot (2.1.10.RELEASE), Hibernate (5.3.13.Final)

I am not sure how to tell a JPARepository to also use the Hibernate UserTypes defined in the Entity class.
For instance lets say I have a UserType for an ID object, that maps the object to a number and vice versa:

```
@TypeDef(type=EntityIdUserType.class, defaultForType=EntityId.class)
@Entity
@Setter
@Getter
...
public class Entity {
 @Id
 @GeneratedValue(strategy = GenerationType.IDENTITY)
 private Integer id;
  
 private EntityId entityId;
}
```

I also have a related JPARepository for this entity.

```
public interface EntityRepository extends JPARepository<Entity, Integer> {
}
```

Now if I create such an Entity and save it via `repo.save()` it works, the user type is used. 
The same happens if I retrieve an entity, e.g. via `findAll()`.

However if I add a method like this to the repository:

```
@Query(value="SELECT * FROM entity WHERE entity_id=:entityId", nativeQuery=true)
public List<Entity> findByEntityId(@Param("entityId") EntityId entityId);
```

The `EntityIdUserType` is NOT applied to the parameter `entityId`, hence the query fails with an error indicating that there is no operator handling integer=bytea (postgres).

How can I tell the repository to also use the user type for parameters?

**Comment by schauder** [comment] 2021-05-31 05:12
Please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

**Comment by stefanrybacki** [comment] 2021-06-01 10:30
Thanks for getting back. Here is a very minimal example of the situation.

https://github.com/stefanrybacki/spring-data-jpa-usertype

I added a test illustrating the behaviour. Note that `addEntity` works using the custom user type. However the `findByDemoId` repository method cannot handle the custom type.

**Comment by schauder** [comment] 2021-06-08 11:46
`@TypeDef` is a Hibernate feature, not one of JPA. It is not at all obvious that Spring Data JPA should support it.

But more importantly: It is up to Hibernate to do any conversions of parameters if it sees so fit. Since we are dealing with a native query I doubt that Hibernate will do such a conversion (or will consider not doing it a bug).

Either way this is only a Spring Data JPA issue if Hibernate on its own would do the conversion. 
I'm therefore closing the issue.
If you can demonstrate it works when directly using an `EntityManager` please reopen the ticket.

**Closed by schauder** 2021-06-08 11:46 UTC
Labels: status: waiting-for-triage

**Comment by stefanrybacki** [comment] 2021-06-08 11:55
@schauder I am aware that `@TypeDef` is a hibernate specific, however it works with other native queries that deserialize such types into the entity. So what is the JPA way of doing provider (Hibernate) independent type mappings, that also work with JPA repositories?

**Comment by schauder** [comment] 2021-06-08 12:07
I haven't thoroughly tested this, but I assume the conversion does not happen for parameters of native queries, and I don't think it should. You could try a JPQL query, i.e. one with `nativeQuery=false`.

**Comment by schauder** [comment] 2021-06-08 13:52
Spring Data does such a conversion, for example Spring Data JDBC. But with Spring Data JPA conversions are done by JPA. And again, I suspect Hibernate does it for JPQL. 

If you want them to do it for SQL you'll need to talk to them, or the JPA team.
