### ISSUE TITLE
Spring Data (2.4+) projection failing while querying LocalDateTime attribute as LocalDate. Same working in SB 2.3.7

### ISSUE THREAD

**Issue by prabhugopal** [spring-projects/spring-data-jpa#2212] opened 2021-05-05 14:36 UTC
We recently upgraded out application to 2.4.5 from 2.3.7, and  we facing below exception with spring data (closed) projection. 

The projection fails with below exception

`Caused by: com.fasterxml.jackson.databind.JsonMappingException: Projection type must be an interface! (through reference chain ***`

I went through the following links as it related to this issue, and assuming it is fixed (partially). 

https://github.com/spring-projects/spring-data-jpa/issues/2121

https://github.com/spring-projects/spring-data-commons/issues/2223

https://jira.spring.io/browse/DATACMNS-1836

But it seems the issue still exists, In our situation we have got entities with attributes of type **LocalDateTime** & the projection attributes with **LocalDate**. The conversion from **LocalDateTime** to **LocalDate** was working without any custom convertor or serializer in SB2.3.7 but after upgrading to SB2.4.5 (tried downgrading to 2.4.0 same issue exists) we get the above exception.

**Comment by schauder** [comment] 2021-05-06 06:43
Please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

**Comment by spring-projects-issues** [comment] 2021-05-13 06:47
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-05-20 06:47
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-05-20 06:47 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback, status: waiting-for-triage
