### ISSUE TITLE
Default null ordering not working [DATAJPA-1821]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-jpa#2110] opened 2020-11-18 09:11 UTC
**[Swapnil Vaidya](https://jira.spring.io/secure/ViewProfile.jspa?name=svaidya401)** opened **[DATAJPA-1821](https://jira.spring.io/browse/DATAJPA-1821?redirect=false)** and commented

I have default null ordering property as 'last' in my Spring Boot Project

`hibernate.order_by.default_null_ordering: last`

`This is not working for the database columns where datatype = text`

`in POSTGRESQL database.`

---
No further details from [DATAJPA-1821](https://jira.spring.io/browse/DATAJPA-1821?redirect=false)

**Comment by SKrabbenborg** [comment] 2021-01-13 14:23
How are you calling the repository when you want the sorting to occur? Since sorting is only applied when the method call actually requests sorting. 

When I have the following in my application.properties:
`spring.jpa.properties.hibernate.order_by.default_null_ordering=first`

firstNames with value null are returned first when I call:
`repository.findAll(Sort.by(Sort.DEFAULT_DIRECTION, "firstName"));`

No sorting occurs when I call: 
`repository.findAll();

**Comment by schauder** [comment] 2021-01-14 08:51
This is a duplicate of #1280 (JPA does not support NULL precedence)

**Closed by schauder** 2021-01-14 08:51 UTC
Labels: type: bug
