### ISSUE TITLE
BadJpqlGrammarException in 3.1.0 when using "escape" in a LIKE query via JPQL

### ISSUE THREAD

**Issue by bwaldvogel** [spring-projects/spring-data-jpa#2975] opened 2023-05-23 20:30 UTC
The following JPA repository method causes a `BadJpqlGrammarException` (`mismatched input 'escape'`) when updating to Spring Data `3.1.0`:

```java
@Query("""
    select a from Animal a
    where a.name like :escapedQuery escape :escapeCharacter
    order by a.id""")
Page<Animal> findByNameLike(@Param("escapedQuery") String escapedQuery,
                            @Param("escapeCharacter") char escapeCharacter,
                            Pageable pageable);
```

```
Caused by: org.springframework.data.jpa.repository.query.BadJpqlGrammarException: Line 2:32 mismatched input 'escape' expecting {<EOF>, ',', AND, EXCEPT, GROUP, INTERSECT, OR, ORDER, UNION}; Bad JPQL grammar [select a from Animal a
where a.name like :escapedQuery escape :escapeCharacter
order by a.id]
	at org.springframework.data.jpa.repository.query.BadJpqlGrammarErrorListener.syntaxError(BadJpqlGrammarErrorListener.java:39)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:543)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)
	at org.springframework.data.jpa.repository.query.HqlParser.start(HqlParser.java:257)
	at org.springframework.data.jpa.repository.query.HqlQueryParser.parseQuery(HqlQueryParser.java:53)
	at org.springframework.data.jpa.repository.query.HqlQueryParser.parse(HqlQueryParser.java:63)
	at org.springframework.data.jpa.repository.query.JpaQueryParserSupport$ParseState.lambda$new$0(JpaQueryParserSupport.java:182)
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:245)
	at org.springframework.data.util.Lazy.get(Lazy.java:114)
	at org.springframework.data.jpa.repository.query.JpaQueryParserSupport$ParseState.getContext(JpaQueryParserSupport.java:194)
	at org.springframework.data.jpa.repository.query.JpaQueryParserSupport.findAlias(JpaQueryParserSupport.java:96)
	at org.springframework.data.jpa.repository.query.JpaQueryEnhancer.detectAlias(JpaQueryEnhancer.java:109)
	at org.springframework.data.jpa.repository.query.StringQuery.<init>(StringQuery.java:86)
	at org.springframework.data.jpa.repository.query.ExpressionBasedStringQuery.<init>(ExpressionBasedStringQuery.java:63)
	at org.springframework.data.jpa.repository.query.AbstractStringBasedJpaQuery.<init>(AbstractStringBasedJpaQuery.java:78)
	at org.springframework.data.jpa.repository.query.SimpleJpaQuery.<init>(SimpleJpaQuery.java:68)
	... 126 more
```

**Comment by gregturn** [comment] 2023-05-24 14:41
This is a duplicate of #2954.

**Closed by gregturn** 2023-05-24 14:41 UTC
Labels: status: duplicate
