### ISSUE TITLE
OutOfMemory Errors after migrating to Spring Boot 3

### ISSUE THREAD

**Issue by Saberos** [spring-projects/spring-data-jpa#3283] opened 2023-12-21 16:09 UTC
After upgrading to Spring Boot 3 our application started throwing `OutOfMemoryError`s while running `@SpringBootTest`s. While analyzing the issue I traced it back to the persistency layer, although the exact cause is still unclear to me. I hope this is the right place to report this issue.

I was able to reproduce the issue in a fairly simple application. Create a bunch of entities, create  `JpaRepository`s for them, and add some `@ManyToOne` relations between the entities. Add a test that attempts to start the context.

Downgrading the exact same application back to Spring Boot 2 (and replacing the Jakarta imports to Javax), and the test will complete even with a heap size of just 128MB. With Spring Boot 3 I tested with up to 8GB, which takes a while but ultimately fails on a `OutOfMemoryError`.

[Spring Boot 2.7.18 project](https://github.com/Saberos/spring-data-jpa-sb2-example)
[Spring Boot 3.2.0 project](https://github.com/Saberos/spring-data-jpa-sb3-example)

To reproduce simply run `./gradlew test`. The Spring Boot 2 project completes successfully while configured with `-Xmx128m`. The Spring Boot 3 project fails while configured with `-Xmx1g`.

**Comment by christophstrobl** [comment] 2023-12-22 08:28
@Saberos thank you for reporting and taking the time to create those sample projects.

**Comment by christophstrobl** [comment] 2023-12-22 09:23
As far as I can tell the problem at hand can be reproduced using plain hibernate. 

```java
StandardServiceRegistry registry = new StandardServiceRegistryBuilder().build();
try {
	new MetadataSources(registry)
		.addAnnotatedClass(EntityA.class)
		.addAnnotatedClass(EntityB.class)
		.addAnnotatedClass(EntityC.class)
		.addAnnotatedClass(EntityD.class)
		.addAnnotatedClass(EntityE.class)
		.addAnnotatedClass(EntityF.class)
		.addAnnotatedClass(EntityG.class)
		... // omitting some lines here
		.addAnnotatedClass(EntityY.class)
		.addAnnotatedClass(EntityZ.class)
		.buildMetadata()
		.buildSessionFactory();
} catch (Exception e) {
	System.err.println(e);
} finally {
	StandardServiceRegistryBuilder.destroy(registry);
}
```

Therefore, I'm closing this one as the problem is caused by an external project. Please report the issue to the hibernate [bug tracker](https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues/). I'd appreciate if you could add the reference to the hibernate ticket here.

**Closed** 2023-12-22 09:26 UTC
Labels: for: external-project, status: declined

**Comment by Saberos** [comment] 2024-01-02 08:45
@christophstrobl thank you for the quick assistance.

I've added a test case based on your example to the test projects and reported the issue on the Hibernate bug tracker here: https://hibernate.atlassian.net/browse/HHH-17601
