### ISSUE TITLE
Add delete(Predicate predicate) to QuerydslJpaPredicateExecutor (and QuerydslPredicateExecutor)

### ISSUE THREAD

**Issue by ddcruver** [spring-projects/spring-data-jpa#2786] opened 2023-02-01 19:37 UTC
We build application-specific query objects to make it easier for our users that we resolve to QueryDSL predicates.  we would like to also reuse the same predicates to perform a delete on the database. Could a function void delete(Predicate predicate) be added to the `org.springframework.data.jpa.repository.support.QuerydslJpaPredicateExecutor` and the interface `org.springframework.data.querydsl.QuerydslPredicateExecutor`

**Comment by mp911de** [comment] 2023-02-02 14:31
Closing as duplicate of spring-projects/spring-data-commons#1022

**Closed by mp911de** 2023-02-02 14:31 UTC
Labels: status: duplicate
