### ISSUE TITLE
findOne(predicate) problem if a entity has EntityGraph

### ISSUE THREAD

**Issue by buzheng** [spring-projects/spring-data-jpa#2823] opened 2023-02-25 07:42 UTC
I hava a problem in a project with sprint boot3 + sprint data jpa + querydsl.

Entity:

```java
@Entity
@NamedEntityGraph(name = "Tenant.Modules", attributeNodes = @NamedAttributeNode("modules"))
public class Tenant extends AbstractEntity {
 
  @ManyToMany(fetch = FetchType.LAZY)
  private Set<BizModule> modules;
}
```

Repository:

```java
public interface TenantRepository extends BaseRepository<Tenant> {
  @Override
  @EntityGraph("Tenant.Modules")
  Optional<Tenant> findOne(Predicate predicate);
}
```

Service Method:

```java
  public Tenant get(@NotBlank String id) {
    return tenantRepository.findOne(QTenant.tenant.id.eq(id)).orElse(null);
  }
```

Tenant and BizModule have a ManyToMany relationship.

The problem is `fineOne(predicate)` only returns two BizModules for a Tenant， envn if the Tenant  has more two BizModules, 

I checked the sql statement and statement parameters, and found out there are a `LIMIT` cause in the sql:

```log
org.hibernate.SQL          : SELECT ... FROM `tenant` t1_0 LEFT JOIN (`tenant_modules` m1_0 JOIN `biz_module` m1_1 ON m1_1.`id` = m1_0.`modules_id`) ON t1_0.`id` = m1_0.`tenants_id` WHERE t1_0.`id` = ? LIMIT ?
org.hibernate.orm.jdbc.bind: binding parameter [1] as [VARCHAR] - [670916171280961536]
org.hibernate.orm.jdbc.bind: binding parameter [2] as [INTEGER] - [2]
```

I don't know how to solve the problem, please help me, thanks.

**Comment by schauder** [comment] 2023-02-27 08:48
Duplicate of #2744

**Closed by schauder** 2023-02-27 08:48 UTC
Labels: status: waiting-for-triage
