### ISSUE TITLE
FetchableFluentQuery ignores 'project'

### ISSUE THREAD

**Issue by trks1970** [spring-projects/spring-data-jpa#2909] opened 2023-04-11 07:12 UTC
spring-data-jpa: 3.0.4

when using ```JpaSpecificationExecutor.findBy(Specification, FetchableFluentQuery)```

and looking at the SQL query generated by hibernate I see that all the entity attributes are queried, not just the ones defined in the ```project``` statement of the FetchableFluentQuery.

Executing:
```
Set<IdProjection> children =
        new HashSet<>(
            jpaChildEntityRepository.findBy(
                ChildEntitySpecification.parent(id),
                fetchableFluentQuery ->
                    fetchableFluentQuery.as(IdProjection.class).project(ChildEntity_.ID).all()));
```

generates the SQL:

```
select c1_0.id,c1_0.description,c1_0.name,c1_0.parent_id,c1_0.revision from child c1_0 where c1_0.parent_id=?
```

complete code is available at: [GitHub](https://github.com/trks1970/specificationProjection)
```ParentServiceTest.deleteWithChildren```

**Comment by schauder** [comment] 2023-04-11 07:43
Duplicate of #2721

**Closed by schauder** 2023-04-11 07:43 UTC
Labels: status: waiting-for-triage
