### ISSUE TITLE
EntityGraph makes two sql queries

### ISSUE THREAD

**Issue by valera21115** [spring-projects/spring-data-jpa#2241] opened 2021-06-17 13:36 UTC
EntityGraph makes two sql queries: Expect join, but get two queries. 
Spring boot version: 2.5.1

In Spring boot version: 2.4.5 EntityGraph works correct.

	@Override
	public T getById(ID id) {

		Assert.notNull(id, ID_MUST_NOT_BE_NULL);
		return em.getReference(getDomainClass(), id);
	}

**Comment by valera21115** [comment] 2021-06-17 13:52
In Spring boot version: 2.4.5 EntityGraph works correct.

**Comment by schauder** [comment] 2021-06-17 14:01
The presence of an EntityGraph doesn't guarantee fetching with a single select.

Please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

Also in this case please demonstrate that this is actually due to Spring Data and not just the way Hibernate or EclipseLink is handling the EntityGraph.

**Comment by genieyr** [comment] 2021-06-18 14:04
https://github.com/valera21115/SpringDataEntityGraph
Run the tests and check its output:
2.4.5
`Hibernate: select user0_.id as id1_1_0_, department1_.id as id1_0_1_, user0_.department_id as departme3_1_0_, user0_.name as name2_1_0_, department1_.name as name2_0_1_ from user user0_ left outer join department department1_ on user0_.department_id=department1_.id where user0_.id=?`
2.5.1
`Hibernate: select user0_.id as id1_1_0_, user0_.department_id as departme3_1_0_, user0_.name as name2_1_0_ from user user0_ where user0_.id=?`
`Hibernate: select department0_.id as id1_0_0_, department0_.name as name2_0_0_ from department department0_ where department0_.id=?`
As a matter of fact backward compatibility has been broken.
Any application that make non-transactional call with @EntityGraph would fail with org.hibernate.LazyInitializationException

**Comment by schauder** [comment] 2021-06-21 09:07
Sorry, which test are you referring to?

**Comment by valera21115** [comment] 2021-06-21 09:39
Sorry, I forgot to update. Could you check again?

**Comment by schauder** [comment] 2021-06-21 12:36
The behaviour seems completely compatible to the entity graph specified. Both selects include `user0.department_id` which is eagerly loading the `department` property.

What gets lazily loaded are the properties of the department, especially the `name` which is not included in the entity graph.

And I'm still convinced this change in behaviour is just Hibernate doing its job and is not caused by Spring Data JPA.

I'm therefore closing this issue. Feel free to request a reopen if you can demonstrate both my assumptions wrong.

**Closed by schauder** 2021-06-21 12:36 UTC
Labels: status: feedback-provided

**Comment by genieyr** [comment] 2021-06-21 17:18
Perhaps there is nothing wrong with Hibernate.
But with overloaded method `Optional<User> getById(int id);` since it is new in v2.5 `T getById(ID id);`
If you change method name for instance to _getUserById_ it works as expected, exactly as in v2.4.
