### ISSUE TITLE
NullPointerException in QueryUtils.createCountQueryFor

### ISSUE THREAD

**Issue by pvandenbroucke** [spring-projects/spring-data-jpa#2822] opened 2023-02-24 11:05 UTC
Hello,

After upgrading the SpringBoot version from 2.7.8 to 2.7.9, I'm getting a NullPointerException : 

> Caused by: java.lang.NullPointerException: null
        at org.springframework.data.jpa.repository.query.QueryUtils.createCountQueryFor(QueryUtils.java:607) ~[spring-data-jpa-2.7.8.jar:2.7.8]
        at org.springframework.data.jpa.repository.query.DefaultQueryEnhancer.createCountQueryFor(DefaultQueryEnhancer.java:49) ~[spring-data-jpa-2.7.8.jar:2.7.8]
        at org.springframework.data.jpa.repository.query.StringQuery.deriveCountQuery(StringQuery.java:119) ~[spring-data-jpa-2.7.8.jar:2.7.8]
        at org.springframework.data.jpa.repository.query.AbstractStringBasedJpaQuery.<init>(AbstractStringBasedJpaQuery.java:72) ~[spring-data-jpa-2.7.8.jar:2.7.8]
        at org.springframework.data.jpa.repository.query.NativeJpaQuery.<init>(NativeJpaQuery.java:53) ~[spring-data-jpa-2.7.8.jar:2.7.8]
        at org.springframework.data.jpa.repository.query.JpaQueryFactory.fromMethodWithQueryString(JpaQueryFactory.java:51) ~[spring-data-jpa-2.7.8.jar:2.7.8]
        at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$DeclaredQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:169) ~[spring-data-jpa-2.7.8.jar:2.7.8]
        at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$CreateIfNotFoundQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:253) ~[spring-data-jpa-2.7.8.jar:2.7.8]
        at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$AbstractQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:93) ~[spring-data-jpa-2.7.8.jar:2.7.8]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lookupQuery(QueryExecutorMethodInterceptor.java:103) ~[spring-data-commons-2.7.8.jar:2.7.8]

In the project, we are using several native queries with `{h-schema}`

Below, you can find a simplified query to reproduce the issue (similar issue happens with update/delete queries) : 
```
@Query(value = "SELECT {h-schema}MY_SEQUENCE.nextval FROM dual", nativeQuery = true)
Long getNextVal();
```

Regards,

Pierrick

**Comment by A1exL** [comment] 2023-02-24 12:08
Have same exception with update queries. As a workaround I had to manually set countQuery.

`@Modifying
@Query(countQuery = "select 1", value = "update some_table set some_column = :theValue", nativeQuery = true)
void updateSomething(@Param("theValue") String theValue);`

Here is the line 607 from org.springframework.data.jpa.repository.query.QueryUtils:
_variable_ is null, so got NPE in variable.contains(",")
if (nativeQuery && (**variable.contains(",")** || "*".equals(variable))) {

**Comment by cmdjulian** [comment] 2023-02-24 14:27
For me it's the same, having a query using a cte:

```kotlin
@Modifying(flushAutomatically = true, clearAutomatically = true)
@Query(
    nativeQuery = true,
    value = """
        WITH some_cte AS (UPDATE some_table2 SET some_id = NULL, some_field = FALSE WHERE id = :id)
        DELETE FROM some_table WHERE id = :id"""
)
override fun deleteById(id: UUID)
```

**Comment by christian-kirschnick** [comment] 2023-02-24 17:22
Same on our sider after updating from boot `3.0.2` to `3.0.3`.

Affected query: 
```java
  @Query(value = "SELECT nextval('sequence')", nativeQuery = true)
  Integer generateSequence();
```

**Comment by ChristianCiach** [comment] 2023-02-24 21:47
Duplicate of https://github.com/spring-projects/spring-data-jpa/issues/2812

This is also a stickied issue at https://github.com/spring-projects/spring-boot/issues

**Comment by martijndebruijn** [comment] 2023-02-27 11:58
I have the same issue with a native delete query. The delete statement returns the number of deleted records
    ```
@Transactional(TxType.REQUIRES_NEW)
    @Modifying
    @Query(
        value = "delete top(:batchSize) from myTable where sent = 1 and creation_date < :creationDate",
        nativeQuery = true
    )
    int deleteByCreationDateBeforeAndSentTrue(@Param("batchSize") int batchSize, @Param("creationDate") LocalDateTime creationDate);

```

Error:
```
Caused by: java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "variable" is null
	at org.springframework.data.jpa.repository.query.QueryUtils.createCountQueryFor(QueryUtils.java:607) ~[spring-data-jpa-2.7.8.jar:2.7.8]
	at org.springframework.data.jpa.repository.query.DefaultQueryEnhancer.createCountQueryFor(DefaultQueryEnhancer.java:49) ~[spring-data-jpa-2.7.8.jar:2.7.8]
```

**Comment by TomKrauss** [comment] 2023-02-27 13:02
Same NPE in my case:
```
    @Modifying
    @Query(value = "truncate table {h-schema}basket_position", nativeQuery = true)
    void deleteAllPositions();
```

**Closed** 2023-02-27 14:34 UTC
Labels: status: duplicate
