### ISSUE TITLE
JPA projection getting 'is no accessor method' in 3.2.0-RC2 and Kotlin 1.9.20

### ISSUE THREAD

**Issue by estigma88** [spring-projects/spring-data-jpa#3221] opened 2023-11-08 02:10 UTC
**Environment:**

Spring Data JPA 3.2.0-RC2
Kotlin 1.9.20
JDK 21

**Problem:**

For a Koltin interface projection over a native Query, we are getting the following error when we try to access a property:

`Invoked method public abstract java.lang.String com.example.issuejpakotlin.AggregateStats.getPipelineId() is no accessor method`

The following is the Kotlin interface:

```
interface AggregateStats {
    fun getPipelineId(): String?
    fun getStdDevKbs(): Double?
}
```

And the JPA repository:

```
interface StatsJpaRepository : JpaRepository<StatsEntity, String> {

    @Query(
        value = """select pipeline_id as pipelineId,
                        stddev(bytes_in_rate) as stdDevKbs
                    from stats
                    where
                        pipeline_id in (?1)
                    group by pipeline_id""", nativeQuery = true
    )
    fun findAllStatsByIdIn(
        pipelineIds: List<String>
    ): List<AggregateStats>
}
```

**How to reproduce:**

We attached a [Spring Boot project](https://github.com/spring-projects/spring-data-jpa/files/13291172/issuejpakotlin.zip), you can run the **test** there.

**Debugging:**

Seems like the _org.springframework.data.util.KotlinBeanInfoFactory_ class cannot find any accessor method in the interface.

This code works fine in Spring Boot 3.0.2 and Kotlin 1.9.20 where _KotlinBeanInfoFactory_ class was not used.

Any help will be appreciated.

**Comment by mp911de** [comment] 2023-11-08 11:03
This looks like a duplicate of spring-projects/spring-data-commons#2964. Can you upgrade to the latest Spring Data snapshots (`3.2.0-SNAPSHOT` for `spring-data-commons`) and retest?

**Comment by estigma88** [comment] 2023-11-15 11:17
We will wait for the GA version to test this issue and come back to you

**Comment by mp911de** [comment] 2023-11-15 13:50
Closing the issue until then.

**Closed by mp911de** 2023-11-15 13:50 UTC
Labels: status: waiting-for-triage, status: feedback-provided
