### ISSUE TITLE
spring data jpa findAll NULLSFIRST does not work 

### ISSUE THREAD

**Issue by Jon3012** [spring-projects/spring-data-jpa#3658] opened 2024-11-05 14:38 UTC
Spring data jpa does not generate hql with NullsFirst .

I am using spring boot version 3.3.4 and trying to retrieve employee (for example) from postgres database using spring data jpa 

Sort.Order order = new Sort.Order(Sort.Direction.ASC, "age", Sort.NullHandling.NULLS_FIRST)

employeeRepository.findAll(Sort.by(order));

while testing , generated query does not contain order by nulls  first.

select id, name from employee order by age **nulls first** is missing in the generated query.

But if i add jpa.properties.hibernate.order_by.default_null_ordering = first in application.yml, then the generated query contains order by nulls first. and it works with nulls_last too. But i need to generate NullsFirst and Nulls last on the columns mentioned on Sort order like the example given .

How to fix this issue where jpa does not generate NullsFirst or NullsLast based on Sort order Null Handling (First and Last) example.. Sort.Order order = new Sort.Order(Sort.Direction.ASC, "age", Sort.NullHandling.NULLS_FIRST)

**Comment by mp911de** [comment] 2024-11-05 15:08
This is a duplicate of #1280. Null precedence is being supported with JPA 3.2+.

**Closed by mp911de** 2024-11-05 15:08 UTC
Labels: status: duplicate
