### ISSUE TITLE
SortBy stop working on Spring boot 2.5.13

### ISSUE THREAD

**Issue by luitas** [spring-projects/spring-data-jpa#2537] opened 2022-05-19 07:36 UTC
On 2.5.12 spring boot it works but in 2.5.13 not working
In my case if i have 
```
pageable = PageRequest.of(pageable.getPageNumber(), pageable.getPageSize(), Sort.by(Sort.Direction.DESC, "inserted"));
return dataRecordRepository.findAllByFilter(pageable,1);

```
and in repository
```
@Query("select r From DataRecord r " +
            "  " +
            "where " +
                    " ( " +
            "       r.adusrId = :userId " +
            "       or EXISTS( select 1 FROM DataRecordDvsRight dr WHERE dr.adusrId = :userId AND dr.dataRecord = r ) " +
            ")")
    Page<DataRecord> findAllByFilter(Pageable pageable, @Param("userId") Long userId);
```
I get an error:
` Invalid path: 'dr.inserted' [select r From com.algoritmusistemos.media.app.entity.DataRecord r   where   (        r.adusrId = :userId        or EXISTS( select 1 FROM com.algoritmusistemos.media.app.entity.DataRecordDvsRight dr WHERE dr.adusrId = :userId AND dr.dataRecord = r ) ) order by dr.inserted desc]`

**Comment by schauder** [comment] 2022-05-19 08:27
This sounds like a duplicate of #2496

**Closed** 2022-05-19 20:24 UTC
Labels: status: waiting-for-triage, in: query-parser

**Comment by gregturn** [comment] 2022-05-19 20:31
Backported to `2.7.x` and `2.6.x`.
