### ISSUE TITLE
Entities are not deleted if they are lazy-loaded and versioned

### ISSUE THREAD

**Issue by StephanPos** [spring-projects/spring-data-jpa#2454] opened 2022-02-22 17:12 UTC
It seems deleting an Entity with `CrudRepository.delete` is not executed in the following example:

given a simple versionend entity with a one-to-many relation
```java
@Entity
@Table(name = "child")
public class ChildEntity {

    @Id
    @GeneratedValue
    private UUID id;

    @Version
    @Column(name = "lockversion")
    private Integer version;

    @OneToMany(mappedBy = "child", fetch = FetchType.LAZY)
    private final Set<ParentEntity> parents = new HashSet<>();

    public Set<ParentEntity> getParents() {
        return parents;
    }
}
```

now given a ParentEntity and a CrudRepository, trying to delete the entity will not be executed. It is silently ignored.
```java
// no delete sql executed
childRepository.delete(parentEntity.getChild());
```
Here is a github repository with working example code https://github.com/StephanPos/spring-data-delete-lazy-entity

The reason for that is - as far as i can see - the isNew() method https://github.com/spring-projects/spring-data-jpa/blob/main/src/main/java/org/springframework/data/jpa/repository/support/JpaMetamodelEntityInformation.java#L242 doesn't take proxy access into account (like the getId() method does) and will fail to detect the version field. Because of the missing/null version field it thinks it is a new entity and doesn't need any deletion.

**Comment by schauder** [comment] 2022-02-23 08:24
I consider it likely that this is cause by normal JPA behaviour because you still have a reference to the `ChildEntity` in the `ParentEntity`

Please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

The example should also demonstrate that this is a Spring Data problem and does not occur if you do the supposedly equivalent action on plain JPA.

**Comment by StephanPos** [comment] 2022-02-23 10:45
There is a working example linked in the ticket. Also the example code is slightly simplified to show the workflow, in the linked github repo it actually does remove the childentity before deleting it.

**Comment by schauder** [comment] 2022-02-23 12:54
Sorry, I missed that. Will take a look.

**Comment by schauder** [comment] 2022-02-23 13:27
The infrastructure detects the version attribute just fine.
The problem seems to be that the entity has a version attribute of `null`, probably due to some lazy loading issue.

I created a PR to demonstrate this: https://github.com/StephanPos/spring-data-delete-lazy-entity/pull/1

**Comment by schauder** [comment] 2022-02-23 13:30
I suggest you create an issue with the Hibernate folks.

I'm closing this for now. 
Let us know if you find indication that this is not a Hibernate issue.

**Closed by schauder** 2022-02-23 13:30 UTC
Labels: status: feedback-provided
