### ISSUE TITLE
BadJpqlGrammarException: no viable alternative at input

### ISSUE THREAD

**Issue by wilx** [spring-projects/spring-data-jpa#3175] opened 2023-09-26 14:37 UTC
I have tried to upgrade to 2023.0.4 from 2022.0.9 and I have more issues with our queries.

The tail end of the call stack of the exception: 

```
Caused by: org.springframework.data.jpa.repository.query.BadJpqlGrammarException: Line 1:60 no viable alternative at input 'coalesce(b.deleted,false)AND'; Bad JPQL grammar [SELECT b FROM Bundle b WHERE NOT coalesce(b.deleted, false) AND b.latestImport = true]
	at org.springframework.data.jpa.repository.query.BadJpqlGrammarErrorListener.syntaxError(BadJpqlGrammarErrorListener.java:39)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:543)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
	at org.springframework.data.jpa.repository.query.JpqlParser.simple_cond_expression(JpqlParser.java:4775)
	at org.springframework.data.jpa.repository.query.JpqlParser.conditional_primary(JpqlParser.java:4637)
	at org.springframework.data.jpa.repository.query.JpqlParser.conditional_factor(JpqlParser.java:4586)
	at org.springframework.data.jpa.repository.query.JpqlParser.conditional_term(JpqlParser.java:4505)
	at org.springframework.data.jpa.repository.query.JpqlParser.conditional_expression(JpqlParser.java:4421)
	at org.springframework.data.jpa.repository.query.JpqlParser.where_clause(JpqlParser.java:3113)
	at org.springframework.data.jpa.repository.query.JpqlParser.select_statement(JpqlParser.java:397)
	at org.springframework.data.jpa.repository.query.JpqlParser.ql_statement(JpqlParser.java:310)
	at org.springframework.data.jpa.repository.query.JpqlParser.start(JpqlParser.java:254)
	at org.springframework.data.jpa.repository.query.JpqlQueryParser.parseQuery(JpqlQueryParser.java:53)
	at org.springframework.data.jpa.repository.query.JpqlQueryParser.parse(JpqlQueryParser.java:64)
	at org.springframework.data.jpa.repository.query.JpaQueryParserSupport$ParseState.lambda$new$0(JpaQueryParserSupport.java:182)
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:245)
	at org.springframework.data.util.Lazy.get(Lazy.java:114)
	at org.springframework.data.jpa.repository.query.JpaQueryParserSupport$ParseState.getContext(JpaQueryParserSupport.java:194)
	at org.springframework.data.jpa.repository.query.JpaQueryParserSupport.renderSortedQuery(JpaQueryParserSupport.java:54)
	... 219 common frames omitted
```

**Comment by wilx** [comment] 2023-09-26 14:44
Yes, EclipseLink 4.0.2. No Hibernate.

**Comment by wilx** [comment] 2023-09-26 15:05
Yes, EclipseLink 4.0.2. No Hibernate.

**Comment by gregturn** [comment] 2023-09-26 15:29
Okay, I thought so. This would be a duplicate of #3170 then.

I am actually close to finishing that up. Simply put, COALESCE expressions in JPQL are only supported in CASE statements. COALESCE expressions however ARE supported in EQL just about anywhere function calls are supported.

**Comment by gregturn** [comment] 2023-09-26 15:38
Actually, what I just wrote isn't 100% true. JPQL DOES support COALESCE in expressions. It just doesn't do that type of expression shown above. For example, this works in JPQL:

```
SELECT b FROM Bundle b WHERE coalesce(b.deleted, false) = true AND b.latestImport = true
```
This example where the `coalesce()` function is compared to another value using ` = true`. Our JPQL grammar indeed rolls that up into a CASE expression which is a legit BOOLEAN expression, and subsequently a comparison function.

What JPQL apparently can't handle (and presumably EQL can handle) is a boolean expression by itself without a comparison operator. I will most assuredly use your query example in the test suite I'm applying to #3170. Thanks!

In the meantime, I am going to close this ticket. Please track the main issue being used to implement EQL parsing.

**Closed by gregturn** 2023-09-26 15:38 UTC
Labels: status: duplicate, status: feedback-provided
