### ISSUE TITLE
FluentQueryByPredicate does not respect property projection when paging

### ISSUE THREAD

**Issue by Rob4001** [spring-projects/spring-data-jpa#2477] opened 2022-03-28 16:50 UTC
Currently using:
`repo.findBy(predicate, query -> {
return query.project("relatedObject").page(pageable);
});`

Where relatedObject is a lazy xToMany relationship on the entity in the repo.
Once the query is completed I still get lazy fetches for all my entities instead of the graph hint being populated to allow a larger but simpler query.

Is there a reason why the read page query does not apply the following logic ?

https://github.com/spring-projects/spring-data-jpa/blob/main/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/support/FetchableFluentQueryByPredicate.java#L176-L182
`
if (!properties.isEmpty()) {
    pagedQuery.setHint(EntityGraphFactory.HINT, EntityGraphFactory.create(entityManager, entityType, properties));
}
`

**Comment by schauder** [comment] 2022-03-30 10:22
Please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

**Comment by spring-projects-issues** [comment] 2022-04-06 10:27
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-04-13 10:27
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-04-13 10:27 UTC
Labels: type: bug, status: waiting-for-feedback, status: feedback-reminder
