### ISSUE TITLE
Spring Boot 3 migration: uuid = bytea problem with derived method querys (UUID and entity types)

### ISSUE THREAD

**Issue by dgallego58** [spring-projects/spring-data-jpa#2889] opened 2023-03-24 15:28 UTC
Hello!

I have migrated a project from 2.7.8 to 3.0.5, with JPA, in 2.7 we mapped an entity (composite) as follows:

```java

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.MapsId;
import jakarta.persistence.Table;

@Entity
@Table(name = Constants.TABLE_NAME_USER_COMPANY_DETAIL, schema = Constants.SCHEMA)
@IdClass(value = UserCompanyDetailCompositeKey.class)
public class UserCompanyDetailData {

    @Id
    @Column(name = Constants.TABLE_COLUMN_ID_USER)
    private UUID userId;
    @Id
    @Column(name = Constants.TABLE_COLUMN_ROL_ID)
    private UUID rolId;
    @Id
    @Column(name = Constants.TABLE_COLUMN_ID)
    private UUID companyId;

    @Column(name = Constants.TABLE_COLUMN_USERNAME_USER, unique = true, length = 50)
    private String username;

    @MapsId("companyId")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = Constants.TABLE_COLUMN_ID, nullable = false)
    private CompaniesData company;

    @MapsId("rolId")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = Constants.TABLE_COLUMN_ROL_ID, nullable = false)
    private RolData rol;

    @MapsId("userId")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = Constants.TABLE_COLUMN_ID_USER, nullable = false)
    private UserData user;
}

```

So far so good, the inserts work, but with the querys that passed an id with UUID.class as argument fails, not just this entity but some casual mappings like mentioned in [#2731](https://github.com/spring-projects/spring-data-jpa/issues/2731#issue-1497084218)

the problem comes with derived methods like `findByCompanyId(UUID companyId)`

it seems the query parses the UUID type as a reference but not its representation, like this:

```java
import org.springframework.data.jpa.repository.EntityGraph;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

public interface UserCompanyDetailDataRepository extends JpaRepository<UserCompanyDetailData, UUID>{


    @EntityGraph(attributePaths = {"company", "user", "rol"})
    List<UserCompanyDetailData> findByCompanyId(UUID companyId);

}
```

the query above generates the following SQL statement:

```log
2023-03-24T10:11:49.557-05:00  INFO 1 --- [nio-8080-exec-2] n.t.d.l.l.SLF4JQueryLoggingListener      :
Name:dataSource, Connection:2218, Time:3, Success:False
Type:Prepared, Batch:False, QuerySize:1, BatchSize:0
Query:["select u1_0.company_id,u1_0.rol_id,u1_0.user_id,c1_0.company_id,c1_0.active,c1_0.city,c1_0.created_at,c1_0.department,c1_0.description,c1_0.doc_num,c1_0.doc_type,c1_0.email,c1_0.facebook_url,c1_0.instagram_url,c1_0.linked_in_url,c1_0.logo_url,c1_0.mdm_key,c1_0.name,c1_0.updated_at,c1_0.use_mdm,c1_0.web_page_url,r1_0.rol_id,r1_0.active,r1_0.description,r1_0.name,u2_0.user_id,u2_0.active,u2_0.doc_num,u2_0.doc_type,u2_0.email,u2_0.first_name,u2_0.last_name,u2_0.middle_name,u2_0.phone,u2_0.second_last_name,u2_0.username,u1_0.username from schnetwk.nt_user_company_detail u1_0 join schnetwk.nt_companies c1_0 on c1_0.company_id=u1_0.company_id join schnetwk.nt_rol r1_0 on r1_0.rol_id=u1_0.rol_id join schnetwk.nt_users u2_0 on u2_0.user_id=u1_0.user_id where u1_0.company_id=?"]
Params:[([B@70d21742)]

2023-03-24T10:11:49.557-05:00  WARN 1 --- [nio-8080-exec-2] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 42883
2023-03-24T10:11:49.557-05:00 ERROR 1 --- [nio-8080-exec-2] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: operator does not exist: uuid = bytea
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
  Position: 777
```

as u can see the value passed `Params:[([B@70d21742)]` is the reference of the object itself, but not the UUID string representation.

to fix it i had to use JPQL using the param value

```java
import org.springframework.data.jpa.repository.EntityGraph;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

public interface UserCompanyDetailDataRepository extends JpaRepository<UserCompanyDetailData, UUID>{


    @Query(value = """
                   select ucd from UserCompanyDetailData ucd
                   left join fetch ucd.company c
                   left join fetch ucd.user u
                   left join fetch ucd.rol r
                   where c.companyId = :companyId
                   """)
    List<UserCompanyDetailData> findByCompanyId(@Param("companyId") UUID companyId);

}
```

then the query is parsed as follows (which works):

```log
2023-03-24T10:15:39.617-05:00  INFO 5456 --- [nio-8080-exec-2] n.t.d.l.l.SLF4JQueryLoggingListener      : 
Name:dataSource, Connection:6, Time:123, Success:True
Type:Prepared, Batch:False, QuerySize:1, BatchSize:0
Query:["select u1_0.company_id,u1_0.rol_id,u1_0.user_id,c1_0.company_id,c1_0.active,c1_0.city,c1_0.created_at,c1_0.department,c1_0.description,c1_0.doc_num,c1_0.doc_type,c1_0.email,c1_0.facebook_url,c1_0.instagram_url,c1_0.linked_in_url,c1_0.logo_url,c1_0.mdm_key,c1_0.name,c1_0.updated_at,c1_0.use_mdm,c1_0.web_page_url,r1_0.rol_id,r1_0.active,r1_0.description,r1_0.name,u2_0.user_id,u2_0.active,u2_0.doc_num,u2_0.doc_type,u2_0.email,u2_0.first_name,u2_0.last_name,u2_0.middle_name,u2_0.phone,u2_0.second_last_name,u2_0.username,u1_0.username from schnetwk.nt_user_company_detail u1_0 join schnetwk.nt_companies c1_0 on c1_0.company_id=u1_0.company_id join schnetwk.nt_rol r1_0 on r1_0.rol_id=u1_0.rol_id join schnetwk.nt_users u2_0 on u2_0.user_id=u1_0.user_id where u1_0.company_id=?"]
Params:[(042fbd2a-ea23-4c66-b1b2-10ec84388fe2)]
```

i had my doubts if i did something wrong... then i reversed the change to use `@EntityGraph` again then the problem disappear (i assume bc of the cache level of hibernate for the same param), then re run the same example and the problems appared again.

So i'm not sure if this is a problem for hibernate or spring data, since the param interpolated becomes the reference of the object passed but not its string representation.

My specs used:

spring boot 3.0.5
java 17 (temurin)
postgresql 14.1
the specified config and dialect:

```yaml
spring:
  application:
    name: ms_company
  jpa:
    properties:
      hibernate:
        default_schema: schnetwk
        create_empty_composites:
          enabled: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
```

as a note i didn't change anything besides the query to replicate the problem while i was migrating the app.

So my fix was to use @Query to specify the query via JPQL

**Comment by schauder** [comment] 2023-03-27 07:12
Please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

**Comment by sebastianmack** [comment] 2023-04-05 10:46
I had a very similar issue `org.postgresql.util.PSQLException: ERROR: operator does not exist: uuid = bytea`.

I fixed it by adding `@JdbcType(UUIDJdbcType.class)`. 

Is this related to this change in Hibernate 6?: https://docs.jboss.org/hibernate/orm/6.0/migration-guide/migration-guide.html#_uuid_mapping_changes
But that would be a bit strange since I've already been using PostgreSQL UUID type. 🤔

**Comment by mp911de** [comment] 2023-05-22 08:51
Closing since this is a Hibernate issue and nothing that we can address.

**Closed by mp911de** 2023-05-22 08:51 UTC
Labels: status: waiting-for-triage, status: feedback-provided
