### ISSUE TITLE
Eclipselink does not implement `Query.getResultStream()`

### ISSUE THREAD

**Issue by vkavalchuk** [spring-projects/spring-data-jpa#2627] opened 2022-09-06 15:42 UTC
Spring Data Jpa starting from version 1.11.8 changed behavior for JpaQueryExecution.doExecute method, it started calls of Query.getResultStream method.

The default implementation for getResultStream is simple getResultList().stream() which is not real streaming, it just put all the data in memory and could come up with Out Of Memory error in some cases.

EclipseLink on a current version 3.0 has not implemented JPA 2.2 getResultStream method, so old behavior with a real streaming has broken.

Possible options that are acceptable here:
1. Introduce some setting to revert behavior as it was on 1.11.7 version (i.e. call persistenceProvider.executeQueryWithResultStream)
2. Revert behavior for eclipselink provider (i.e. call persistenceProvider.executeQueryWithResultStream)

**Comment by schauder** [comment] 2022-09-07 06:18
Interesting, I wasn't aware that we had proper streaming support for EclipseLink. Could you please provide a reproducer of what worked pre 1.11.8 and doesn't work with a current version?

Please make sure to include the database either as an in memory database or as Testcontainers.

**Comment by vkavalchuk** [comment] 2022-09-08 13:10
I need a time to prepare it. I'll put just extended description for now here:
Original [issue#1692](https://github.com/eclipse-ee4j/eclipselink/issues/1692) is related to eclipselink library that is not overriding JPA 2.2 getResultStream default method.

Connected [issue#2627](https://github.com/spring-projects/spring-data-jpa/issues/2627) is related to [spring-data changes](https://github.com/spring-projects/spring-data-jpa/blob/1.11.x/src/main/java/org/springframework/data/jpa/repository/query/JpaQueryExecution.java#L361).
Old behavior relied on [other logic](https://github.com/spring-projects/spring-data-jpa/blob/1.10.x/src/main/java/org/springframework/data/jpa/repository/query/JpaQueryExecution.java#L327)

getResultStream method [is not implemented](https://github.com/eclipse-ee4j/eclipselink/search?q=getResultStream) on eclipselink side. That's why instead of ScrollableCursor default implementation is in use, which is simple java stream getResultList().stream().

Actually this brakes traditional streaming on DB side.
Current default implementation has disadvantages:
 * Application have to wait full pack of data.
 * Memory consumption increased, depending on actual table size.

From that perspective it's highly recommended to add an option to revert [old bavavior](https://github.com/spring-projects/spring-data-jpa/blob/1.10.x/src/main/java/org/springframework/data/jpa/repository/query/JpaQueryExecution.java#L327)

**Comment by odrotbohm** [comment] 2022-09-13 08:55
If the current production version of Eclipselink doesn't implement `getResultStream()` you need to discuss this with them, not us. We rely on the method being available through the level of JPA API we support and just use that method.

There's a 4.0 RC2 version available for Eclipselink. I just checked, but it looks like that version doesn't implement that method properly, either.

**Comment by schauder** [comment] 2022-09-13 09:38
@odrotbohm did we ever have streaming support for EclipseLink that went beyond using `getResultStream()`? I know there was a Hibernate specific implementation back when they had streaming support, but it wasn't part of the JPA spec. But for EclipseLink I'm not aware of such an implementation at any time.

**Comment by vkavalchuk** [comment] 2022-09-13 10:08
Here is the reproducer https://github.com/vkavalchuk/spring-boot-eclipselink

>If the current production version of Eclipselink doesn't implement getResultStream() you need to discuss this with them
Right it's an issue of eclipse-link project and I've created the issue for them.
From the other side spring-data forces using of getResultStream.
Is it possible to add some setting so that it will be possible to fall back to legacy stream execution?
I.e.
			// JPA 2.2 on the classpath
			if (eclipselinkStreaming == true && streamMethod != null) {
				return ReflectionUtils.invokeMethod(streamMethod, jpaQuery);
			}

**Comment by odrotbohm** [comment] 2022-09-13 10:08
Yes, prior to the method introduced in JPA proper, we had support implemented solely [on our side](https://github.com/spring-projects/spring-data-jpa/blob/4b0e52c2c09225c17e3bda491d116622cb01a702/src/main/java/org/springframework/data/jpa/provider/PersistenceProvider.java#L472-L526) by using provider-specific API to obtain a cursor and use that behind a stream. We theoretically could re-instantiate that support, but that kind of subverts the idea of using JPA as advertised.

**Comment by odrotbohm** [comment] 2022-09-13 10:13
> From the other side spring-data forces using of getResultStream.
> Is it possible to add some setting so that it will be possible to fall back to legacy stream execution?

I'd argue that we're not in the business of knowing about certain limitations of a JPA implementation and proactively work around those. Eclipselink is the reference implementation of JPA. If it doesn't natively support streaming results, you can/have to switch to a different persistence provider, or implement query methods supposed to stream manually. My core point here is that if we fix this on our side, where do we draw the line? Our custom support existed because *JPA* didn't support it. Not that it does, there's no need for us to replicate functionality that is actually mandated by JPA, even if – as this case shows – optionally. Otherwise we're on a slippery slope to Spring Data Eclipselink / Hibernate etc.

I can only recommend beating the drum for that support to be added to Eclipselink natively, which would also have the positive side effect that JPA users not using Spring Data would actually get access to it.

**Comment by odrotbohm** [comment] 2022-09-13 10:19
I appreciate the reproducer, but I'd argue that neither Boot nor Spring Data are relevant to the problem to be solved. Reducing this to pure Eclipselink usage and attaching it to the ticket you already created with their tracker would be helpful.

**Comment by odrotbohm** [comment] 2022-09-13 11:23
It looks like the JPA spec lead also thinks this should be brought up with Eclipselink itself: https://www.eclipse.org/lists/jpa-dev/msg00158.html

**Comment by gregturn** [comment] 2022-09-29 15:11
Since this is presently an EclipseLink issue, I'm going to close it. If there are new developments, we can revisit this in the future.

**Closed by gregturn** 2022-09-29 15:11 UTC
Labels: status: declined
