### ISSUE TITLE
Pageable.Sort.Order: NullHandling is not taken into consideration

### ISSUE THREAD

**Issue by lonely-development** [spring-projects/spring-data-jpa#2222] opened 2021-05-31 14:13 UTC
I'm currently trying to build some dynamic rules on how the persistence layer should handle null values (`NATIVE`,  `NULLS_FIRST` & `NULLS_LAST`).

While testing I notice that the `Order.nullHanding` is not taken into consideration  when Spring builds a JPA query.

The issue seems to be present when using `PagingAndSortingRepository.findAll(Pageable)`  and when using `@Query` based repository methods:
```
    @Query("FROM Entity")
    fun page(pageable: Pageable) : Page<TaskEntity>
```

For the `@Query` approach you can check `QueryUtils.getOrderClause()` to see that `Order.nullHandling` is completely ignored (not sure about the `PagingAndSortingRepository` use case).

**Comment by schauder** [comment] 2021-05-31 14:45
Duplicate of #1280

**Closed by schauder** 2021-05-31 14:45 UTC
