### ISSUE TITLE
Spring data JPA fails to sort with JSONB column

### ISSUE THREAD

**Issue by abirami-els** [spring-projects/spring-data-jpa#3563] opened 2024-08-07 06:16 UTC
I'm using Spring Data JPA (v3.0.10) to sort and paginate a table in Postgres.

I'm facing issue when I try to sort by JSONB column.
```java
Pageable p = PageRequest.of(1,19, JpaSort.unsafe(Sort.Direction.ASC, "publicationSchedule->>'permissionDeadline'"));
```
Exception:
```
Request processing failed: org.springframework.data.mapping.PropertyReferenceException: No property 'publicationSchedule->>'permissionDeadline'' found for type 'Publication'] with root cause
org.springframework.data.mapping.PropertyReferenceException: No property 'publicationSchedule->>'permissionDeadline'' found for type 'Publication'
	at org.springframework.data.mapping.PropertyPath.<init>(PropertyPath.java:90) ~[spring-data-commons-3.2.4.jar:3.2.4]
```

**Comment by christophstrobl** [comment] 2024-08-07 11:26
duplicate of: #1997

**Comment by mp911de** [comment] 2024-08-07 12:44
It is and it will be handled through the referenced ticket.

**Closed by mp911de** 2024-08-07 12:44 UTC
Labels: status: duplicate
