### ISSUE TITLE
Pageable NamedNativeQuery defined in orm.xml not work properly.

### ISSUE THREAD

**Issue by lllyyylll2** [spring-projects/spring-data-jpa#2172] opened 2021-03-10 04:48 UTC
I have defined a native query with default Repository method name.  
When I execute the query method I  got the error:
```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0; nested exception is java.lang.IllegalArgumentException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
org.springframework.dao.InvalidDataAccessApiUsageException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0; nested exception is java.lang.IllegalArgumentException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
```
with the stacktrace:
``` 
Caused by: java.lang.IllegalArgumentException: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.hibernate.internal.AbstractSharedSessionContract.buildQueryFromName(AbstractSharedSessionContract.java:902)
	at org.hibernate.internal.AbstractSharedSessionContract.createNamedQuery(AbstractSharedSessionContract.java:997)
	at org.hibernate.internal.AbstractSharedSessionContract.createNamedQuery(AbstractSharedSessionContract.java:113)
	at jdk.internal.reflect.GeneratedMethodAccessor134.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:366)
	at com.sun.proxy.$Proxy1669.createNamedQuery(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor134.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:314)
	at com.sun.proxy.$Proxy1669.createNamedQuery(Unknown Source)
	at org.springframework.data.jpa.repository.query.NamedQuery.doCreateCountQuery(NamedQuery.java:190)
	at org.springframework.data.jpa.repository.query.NamedQuery.doCreateCountQuery(NamedQuery.java:43)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.createCountQuery(AbstractJpaQuery.java:254)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$PagedExecution.count(JpaQueryExecution.java:183)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$PagedExecution.lambda$doExecute$0(JpaQueryExecution.java:178)
	at org.springframework.data.repository.support.PageableExecutionUtils.getPage(PageableExecutionUtils.java:62)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$PagedExecution.doExecute(JpaQueryExecution.java:177)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:88)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:154)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:142)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor$QueryMethodInvoker.invoke(QueryExecutorMethodInterceptor.java:195)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:152)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:130)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	... 66 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.hibernate.internal.AbstractSharedSessionContract.resultClassChecking(AbstractSharedSessionContract.java:959)
	at org.hibernate.internal.AbstractSharedSessionContract.createNativeQuery(AbstractSharedSessionContract.java:918)
	at org.hibernate.internal.AbstractSharedSessionContract.buildQueryFromName(AbstractSharedSessionContract.java:896)
	... 98 more
```
The Query Method define as :
``` java
Page<TaskInfoInner> findMyTaskListV2(@Param("samId") Integer samId, @Param("inspCatId") Integer inspCatId,
                        @Param("yr") Integer yr, @Param("mth") Integer mth, @Param("entName") String entName,
                        @Param("personId") int personId, @Param("unitId") int unitId,
                        @Param("officeUnitId") int officeUnitId, Pageable page);
```

``` xml
<named-native-query name="Plan.findMyTaskListV2">
        <query>
            <![CDATA[ 
            select it.id id,et.id entId,et.name entName,et.reg_Addr addr,it.fr_Time frTime,it.to_Time toTime,
	            it.period,isnull(it.exec_State,0) execState,it.person_Names personNames,
	            case when it.yr_Plan_id is null then 0 else 1 end ifYr,
	            s.sam_id samId, s.insp_Cat_id inspCatId,c.name inspCatName,s.spcl_id spclId,sp.name spclName,
	            ip.id inspId,ip.start_Time inspStartTime,ip.finish_Time inspFinishTime,ip.person_Names inspPersonNames
            from T_PLAN it left join T_ENT et on it.ENT_ID=et.ID
            left join T_PLAN_SAM s on s.PLAN_ID=it.ID
            left join T_SAM_INSP_CAT c on c.ID=s.INSP_CAT_ID
            left join T_SPCL sp on sp.ID=s.SPCL_ID
            left join T_INSP ip on ip.ID=it.INSP_ID
            where it.insp_id is null and (:samId is null or s.sam_id=:samId)
                and (:inspCatId is null or s.insp_Cat_id=:inspCatId)
                and (:yr is null or year(it.fr_Time)=:yr)
                and (:mth is null or month(it.fr_Time)=:mth)          
                and (
                    :personId is null or (
                        exists(select 1 from T_plan_Person p1 where p1.plan_id=it.id and p1.person_id=:personId) 
                        or (
                            not exists(select 1 from T_plan_Person p1 where p1.plan_id=it.id) 
                            and (it.unit_id=:unitId or it.office_Unit_id=:officeUnitId)
                        )
                    )
                ) 
                and (:entName is null or et.name like :entName)
            ]]>
        </query>
    </named-native-query>
    <named-native-query name="Plan.findMyTaskListV2.count">
        <query>
        <![CDATA[
        select count(0) as size
        from T_PLAN it left join T_ENT et on it.ENT_ID=et.ID
        left join T_PLAN_SAM s on s.PLAN_ID=it.ID
        left join T_SAM_INSP_CAT c on c.ID=s.INSP_CAT_ID
        left join T_SPCL sp on sp.ID=s.SPCL_ID
        left join T_INSP ip on ip.ID=it.INSP_ID
        where it.insp_id is null and (:samId is null or s.sam_id=:samId)
            and (:inspCatId is null or s.insp_Cat_id=:inspCatId)
            and (:yr is null or year(it.fr_Time)=:yr)
            and (:mth is null or month(it.fr_Time)=:mth)          
            and (
                :personId is null or (
                    exists(select 1 from T_plan_Person p1 where p1.plan_id=it.id and p1.person_id=:personId) 
                    or (
                        not exists(select 1 from T_plan_Person p1 where p1.plan_id=it.id) 
                        and (it.unit_id=:unitId or it.office_Unit_id=:officeUnitId)
                    )
                )
            ) 
            and (:entName is null or et.name like :entName)
            ]]>
        </query>
    </named-native-query>
```
Is this a bug?

**Comment by schauder** [comment] 2021-03-10 07:58
Please provide a reproducer for this. Please make sure it includes everything necessary, including the database, either as an in-memory database or as via Testcontainers.

**Comment by spring-projects-issues** [comment] 2021-03-17 08:03
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-03-24 08:03
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-03-24 08:03 UTC
Labels: status: feedback-reminder, status: waiting-for-feedback
