### ISSUE TITLE
`CONCAT` of `LIKE` with percentage (`%`) literal fails for `null` values

### ISSUE THREAD

**Issue by SimSonic** [spring-projects/spring-data-jpa#3041] opened 2023-06-27 05:47 UTC
Hello! I have such repository method (simplified):

```java
@Query("""
        SELECT pe AS profile,
               device AS profileDevice
        FROM ProfileEntity AS pe
        LEFT JOIN ProfileDeviceEntity AS device
            ON device.profile = pe
        WHERE (pe.lastSeen              IS NULL OR (pe.lastSeen >= :#{#filter.dateStart} AND pe.lastSeen <= :#{#filter.dateEnd}))
          AND ( :#{#filter.id}          IS NULL OR pe.id              = :#{#filter.id} )
          AND ( :#{#filter.login}       IS NULL OR pe.login        LIKE :#{#filter.login}% )
          AND ( :#{#filter.preset}      IS NULL OR pe.preset       LIKE :#{#filter.preset}% )
          AND ( :#{#filter.lastName}    IS NULL OR pe.lastName        = :#{#filter.lastName} )
          AND ( :#{#filter.firstName}   IS NULL OR pe.firstName       = :#{#filter.firstName} )
          AND ( :#{#filter.application} IS NULL OR device.application = :#{#filter.application} )
          AND ( :#{#filter.platform}    IS NULL OR device.platform    = :#{#filter.platform} )
          AND ( device.lastSeen         IS NULL OR device.lastDevice IS TRUE )
        ORDER BY pe.id DESC
        """)
Page<AdminProfileProjection> profilesForJournal(Pageable pageable, ProfileJournalFilter filter);
```

Columns are defined simply:

![image](https://github.com/spring-projects/spring-data-jpa/assets/2697754/73ff3953-14fd-425d-9ecf-a7c1281259ee)

![image](https://github.com/spring-projects/spring-data-jpa/assets/2697754/d6f4e27f-cf05-41ce-a8e2-f54728b4f7e0)

After I upgraded Spring Boot from 2.7.12 to 2.7.13 I've received failing test which calls this method. The error:

```
Caused by: org.postgresql.util.PSQLException: ERROR: operator does not exist: character varying ~~ bytea 
  Hint: No operator matches the given name and argument types. You might need to add explicit type casts. 
  Position: 1805 
 at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse([QueryExecutorImpl.java:2713](https://queryexecutorimpl.java:2713/))
...
```

I've discovered that this is caused by this feature: https://github.com/spring-projects/spring-data-jpa/issues/2939

How can I fix query? Or this is implementation bug?

**Comment by mp911de** [comment] 2023-06-27 14:51
Can you please attach the SQL that is generated from the query?

**Comment by SimSonic** [comment] 2023-06-27 15:25
> Can you please attach the SQL that is generated from the query?

A little bit cropped SQL:

```sql
select profileent0_."id"                   as id1_64_0_,
       profiledev1_."id"                   as id1_68_1_,
       profileent0_."blocked"              as blocked5_64_0_,
       profileent0_."coordinates_timezone" as coordina6_64_0_,
       profileent0_."coordinates_updated"  as coordina7_64_0_,
       profileent0_."login"                as dess_log9_64_0_,
       profileent0_."first_name"           as first_n11_64_0_,
       profileent0_."gps_timezone"         as gps_tim14_64_0_,
       profileent0_."last_name"            as last_na15_64_0_,
       profileent0_."last_seen"            as last_se16_64_0_,
       profileent0_."latitude"             as latitud17_64_0_,
       profileent0_."longitude"            as longitu18_64_0_,
       profileent0_."preset"               as preset20_64_0_,
       profiledev1_."application"          as applicat2_68_1_,
       profiledev1_."version"              as version3_68_1_,
       profiledev1_."auth_domain_type"     as auth_dom4_68_1_,
       profiledev1_."created"              as created5_68_1_,
       profiledev1_."installment_id"       as installm6_68_1_,
       profiledev1_."last_device"          as last_dev7_68_1_,
       profiledev1_."last_seen"            as last_see8_68_1_,
       profiledev1_."mobile_platform"      as mobile_p9_68_1_,
       profiledev1_."platform_version"     as platfor10_68_1_,
       profiledev1_."profile_id"           as profile11_68_1_
from "e2e_public"."profiles" profileent0_
         left outer join "e2e_public"."profiles_devices" profiledev1_ on (profiledev1_."profile_id" = profileent0_."id")
where (profileent0_."last_seen">=? and profileent0_."last_seen"<=? or profileent0_."last_seen" is null)
  and (? is null or profileent0_."id"=?)
  and (? is null or profileent0_."login" like (?||'%'))
  and (? is null or profileent0_."preset" like (?||'%'))
  and (? is null or profileent0_."last_name"=?)
  and (? is null or profileent0_."first_name"=?)
  and (? is null or profiledev1_."application"=?)
  and (? is null or profiledev1_."mobile_platform"=?)
  and (profiledev1_."last_seen" is null or profiledev1_."last_device" = true)
order by profileent0_."id" DESC
limit ?
```
so this lines are under question:
```sql
  and (? is null or profileent0_."login" like (?||'%'))
  and (? is null or profileent0_."preset" like (?||'%'))
```

**Comment by gregturn** [comment] 2023-06-27 19:33
Just to be clear, we used to take the wildcard and alter the input parameter by applying it.

Thus, `LIKE :#{#filter.preset}%` would be expanded by SpEL into `LIKE :preset%` (I'm not sure what your SpEL expression ACTUALLY expands to, but I'm just assuming `preset`), which would then be turned into `LIKE :preset` with the actual argument going from `foo` to `foo%`. 

#2939 fixes the risk you face if you had `:preset` more than once in the query, with the last instance getting/not getting that wildcard.

Now we do `LIKE :#{#filter.preset}%` -> `LIKE :preset%` -> `LIKE :preset || '%'`, with the actual input untouched. As @mp911de said, Postgres documentation shows this as supported, so something else is at play that is making it seem to transform things into a `bytea` operation.

I don't know if you can share you complete entity type as well as the arguments fed to that query. And I see you're using a projection, so that would be useful to know as well.

**Comment by gregturn** [comment] 2023-06-27 19:36
Something else that could be at play is usage of Cyrillic alphabet as I see in the screenshot. I don't know if that's an issue at all or not, but if the data doesn't quite fit strings, the database could be trying to "help" by migrating to raw binary strings, and throwing everything for a loop. That would also be fitting in its warning to use a cast operation.

**Comment by SimSonic** [comment] 2023-06-28 05:12
> I don't know if you can share you complete entity type as well as the arguments fed to that query. And I see you're using a projection, so that would be useful to know as well.

Nothing interesting here.

Entity:

```java
@Entity
@Table(name = "profiles")
@Getter
@Setter
@ToString
public class ProfileEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, unique = true)
    private Long id;

    @Column(name = "login")
    private String login;

    @Column(name = "phone")
    private String phone;

    @Column(name = "email")
    private String email;

    @Column(name = "last_name")
    private String lastName;

    @Column(name = "first_name")
    private String firstName;

    @Column(name = "preset")
    private String preset;

    @Column(name = "last_seen")
    private Instant lastSeen;

    @Column(name = "latitude")
    private double latitude;

    @Column(name = "longitude")
    private double longitude;

    @Column(name = "coordinates_updated")
    private Instant coordinatesUpdated;

    @Column(name = "fis_timezone")
    private Integer fisTimezone;

    @Column(name = "coordinates_timezone")
    private Integer coordinatesTimezone;

    @Column(name = "gps_timezone")
    private Integer gpsTimezone;

    @Column(name = "blocked", nullable = false)
    private boolean blocked;
}
```

Filtering fields DTO:

```java
@lombok.Value
@lombok.Builder
@lombok.Jacksonized
@JsonInclude(JsonInclude.Include.NON_NULL)
public class ProfileJournalFilter {

    Long id; // nullable...

    String login; // nullable!

    String preset; // nullable!

    @NotNull
    @Builder.Default
    Instant dateStart = TimeUtils.FILTER_DATE_TIME_START;

    @NotNull
    @Builder.Default
    Instant dateEnd = TimeUtils.FILTER_DATE_TIME_END;

    String lastName; // nullable!

    String firstName; // nullable!

    MobileApplication application; // it's enum, nullable

    MobilePlatform platform; // // it's enum, nullable
}
```

Projection:

```java

public interface AdminProfileProjection {

    ProfileEntity getProfile();

    ProfileDeviceEntity getProfileDevice();
}

```

THe root of a problem is nullability of string fields in DTO. Before #2939 if `preset` was null it generated code like
```sql
... AND NULL IS NULL OR presetr LIKE NULL ...
```
but now it is:
```sql
... AND NULL IS NULL OR preset LIKE NULL || '%'
```
so PostgreSQL cannot concatenate NULL with '%' because interprets it as bytea.

**Comment by mp911de** [comment] 2023-06-28 08:25
> so PostgreSQL cannot concatenate NULL with '%' because interprets it as bytea.

Thanks for the insight. That raises the general question how `LIKE :#{#filter.login}%` is supposed to work in the case of `null` as `null` cannot be combined with `%` (regardless of the underlying system). I suggest that you provide a property for SpEL usage that renders `login` + `%` on your side if the `login` field is not null.

**Comment by SimSonic** [comment] 2023-06-28 10:55
No any other logic on my side. I think implementation before #2939 just did that (unexpectedly) :)

**Comment by mp911de** [comment] 2023-06-28 13:06
Our code previously made an assumption regarding representing null values in the context of `LIKE` with percentage. We cannot rewrite the bound parameter value because if the parameter is used multiple times, the bound value no longer represents the actual value but the rewritten variant.

I wonder whether we could isolate `LIKE` with `%` literals so that we create a derived binding value and fall back to the previous approach @gregturn.

**Comment by gregturn** [comment] 2023-06-28 14:28
> I wonder whether we could isolate LIKE with % literals so that we create a derived binding value and fall back to the previous approach @gregturn.

I can look into this. I'm not quite certain where this happens, but it's worth a shot.

**Comment by gregturn** [comment] 2023-06-28 20:00
Looks like transforming a LIKE with wildcards into a CONCAT function happens at a different point in time then when the arguments are fed in. Essentially, we can't tell that in advance if there will be `null`.

However, JPA has the `COALESCE` function that can wrap the argument, with a fallback value of an empty string. This provides a succinct, spec-compliant way to handle potential nulls.

To illustrate:

```
@Query("select e from EmployeeWithName e where e.name like %:partialName%")
List<EmployeeWithName> customQueryWithNullableParam(@Nullable @Param("partialName") String partialName);
```

This query, when a partial name is provided, will wrap it in wildcards. If null, the COALESCE function will collapse to `''`, which being CONCAT'd with wildcards, would match everything, which sounds correct.

**Comment by SimSonic** [comment] 2023-06-29 02:58
@gregturn I found [this question on SO](https://stackoverflow.com/questions/20754466/error-coalesce-types-bytea-and-character-varying-in-postgresql) and it makes me doubt that simple `(LIKE COALESCE (:param, '') || '%')` will be enough.

**Comment by SimSonic** [comment] 2023-06-29 03:52
For my query I've found a solution:
```sql
AND ( :#{#filter.preset}      IS NULL OR pe.preset       LIKE CONCAT(COALESCE(CAST(:#{#filter.preset} AS string), ''), '%'))
```
or even
```
AND (pe.preset LIKE CONCAT(COALESCE(CAST(:#{#filter.preset} AS string), ''), '%'))
```
because right part began to support nullish values in filter. The only thing that worries me is that will postgresql planner collapse `LIKE '%'` into TRUE or not.

**Comment by gregturn** [comment] 2023-06-29 14:07
I'll try the CAST operation. 

But it's true that if you have a `null` value combined with a wildcard, it will simply collapse into the wildcard and thus match everything. If you are wanting a different behavior, you may have to rethink usage of a wildcard. What DOES a `null` combine with a wildcard mean to YOU when it comes to LIKE operations?

**Comment by gregturn** [comment] 2023-06-29 14:39
Okay, it looks like `CAST( :parm as string)` is purely Hibernate and will fail with EclipseLink, but `CAST(:parm as text)` seems to be more universal.

**Comment by SimSonic** [comment] 2023-06-30 03:48
> What DOES a null combine with a wildcard mean to YOU when it comes to LIKE operations?

It is a hard question =)

My opinion is that it should be consistent with all implementations of the JPA and RDBMSes and work the same and documented. In fact, two options of concatenating null with '%' — casting to NULL and casting to '%' — are acceptable. But the fall of the request with an exception is undesirable...

**Comment by SimSonic** [comment] 2023-06-30 03:49
> Okay, it looks like `CAST( :parm as string)` is purely Hibernate and will fail with EclipseLink, but `CAST(:parm as text)` seems to be more universal.

Hm, `CAST (:param AS TEXT)` failed for me ... That's why a wrote `string`.

**Comment by gregturn** [comment] 2023-07-04 15:21
> Hm, CAST (:param AS TEXT) failed for me ... That's why a wrote string.

This implies we need a provider-oriented function that decides WHICH variant to apply. Basically, Hibernate -> `CAST(:param as string)` while perhaps everyone else does `CAST(:param as text)`. Integration testing would be in order.

> My opinion is that it should be consistent with all implementations of the JPA and RDBMSes and work the same and documented. In fact, two options of concatenating null with '%' — casting to NULL and casting to '%' — are acceptable. But the fall of the request with an exception is undesirable...

If you have `null` with wildcards on either end, we could then collapse that to an empty string using COALESCE and apply wildcards.

If we had a data set of `["Frodo Baggins", "Bilbo Baggins"]`, and a query method like:

```java
@Query("select e from Employee e where e.name LIKE '%:name%'")
List<Employee> findMatch(String name);
```

that sort of rule should yield:

`findMatch("Frodo")` => `["Frodo Baggins"]`
`findMatch("Bilbo")` => `["Bilbo Baggins"]`
`findMatch("Baggins")` => `["Frodo Baggins", "Bilbo Baggins"]`
`findMatch("")` => `["Frodo Baggins", "Bilbo Baggins"]`
`findMatch(null)` => `["Frodo Baggins", "Bilbo Baggins"]`

Does that sound fitting?

**Comment by SimSonic** [comment] 2023-07-04 17:08
For me it's an open question what is the most reasonable result for `findMatch(null)` and I'm not able to choose between query `LIKE '%%'` (which will result into `["Frodo Baggins", "Bilbo Baggins"]`) or `LIKE NULL` (results in `[]`).

First variant looks like backward-compatible, second is a little bit more intuitive.

I hope for your informed decision.

**Comment by gregturn** [comment] 2023-07-07 21:13
For the record, I favor the former over the latter. If someone puts wildcards into their `LIKE` expression, I think somehow pivoting toward `LIKE NULL` is going too far. They need to write that deliberately.

I have tweaked things so that the `CAST` function is based on whether or not we're using Hibernate.

I'd also invite @mp911de 's opinion for further feedback.

**Comment by gregturn** [comment] 2023-07-07 21:18
I need to craft some more test cases.

**Comment by gregturn** [comment] 2023-07-21 18:59
Resolved.  Merged to `main`.

**Closed by gregturn** 2023-07-21 18:59 UTC
Labels: type: bug, status: feedback-provided

**Comment by gregturn** [comment] 2023-07-21 19:41
Backported to `3.1.x` and `3.0.x`.

**Comment by SimSonic** [comment] 2023-07-26 18:00
@gregturn hi, will it be backported to 2.7.15?

**Comment by gregturn** [comment] 2023-08-07 20:53
No. There are simply too many differences between Spring Data JPA 2.7.x and 3.x to backport it that far.

**Comment by mp911de** [comment] 2023-08-08 09:05
@gregturn how about us rolling back the conflicting change in Spring Data JPA 2.7.x? There are workarounds to omit named parameter reuse and judging from the impact of `CONCAT`, the previous variant seems less harmful to existing applications.

**Comment by nilshartmann** [comment] 2023-10-20 18:29
I may have the same or a similar problem that first occures in Spring Boot 3.1.5. (I tested 3.1.1 to 3.1.4 and my query works). In my query I have a `where` clausel `where :t is null or b.title like concat(:t, '%')`. If `t` is null, the error occures.

```
org.springframework.dao.InvalidDataAccessResourceUsageException: JDBC exception executing SQL [select b1_0.id,b1_0.title from books b1_0 where ? is null or b1_0.title like (?||'%') escape ''] [ERROR: operator does not exist: text ~~ bytea
  Hinweis: No operator matches the given name and argument types. You might need to add explicit type casts.
```

SQL:
```sql
select
        b1_0.id,
        b1_0.title 
    from
        books b1_0 
    where
        ? is null 
        or b1_0.title like (?||'%') escape ''
```


You can find a reproducable test case here: https://github.com/nilshartmann/spring-jpa-concat

 - Example Query: https://github.com/nilshartmann/spring-jpa-concat/blob/main/src/main/java/com/example/springjpaconcat/BookRepository.java#L11
 - There is [one test method](https://github.com/nilshartmann/spring-jpa-concat/blob/main/src/test/java/com/example/springjpaconcat/SpringJpaConcatApplicationTests.java#L18) that fails with Spring Boot 3.1.5 but not with 3.1.4
 
Again, I'm not sure, if that is the same problem as the original one. If you have any other pointers for me, please let me know. Thanks a lot!
