### ISSUE TITLE
app throws "Applying Null Precedence using Criteria Queries is not yet supported." exception in v3.4.0 but works with v3.3.6

### ISSUE THREAD

**Issue by kctang** [spring-projects/spring-data-jpa#3704] opened 2024-12-05 09:32 UTC
I'm migrating a spring boot v2.7.x app to v3.4.0 At runtime, i'm getting `"Applying Null Precedence using Criteria Queries is not yet supported."` exception thrown.

https://github.com/spring-projects/spring-data-jpa/blob/7f13a04c414ad210e30ef647fda75590e28526cb/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/query/QueryUtils.java#L757

The exception was thrown when trying to execute my repository interface's method that looks something like `Page<Xxx> findByXxxAndYyy(String xxx, yyy, Pageable pageable);`.

I tried to switch to spring boot v3.3.6 and the app works without issue, so only seems to affect v3.4.0.

I placed a comment in a [related issue](https://github.com/spring-projects/spring-data-jpa/pull/3529#issuecomment-2519706081).

Looks like a bug to me.

Thanks for reading & hope this issue can be solved soon.

**Comment by mp911de** [comment] 2024-12-10 13:32
Null precedence wasn't ever supported using Criteria Queries because JPA doesn't specify (until JPA 3.2) the necessary API. We just never raised awareness that this isn't working. We consider leniently accepting and silently dropping sort definitions a potential source of bugs that easily goes unnoticed. Therefore, we introduced an exception to alert you that the intended null sorting behavior isn't available. If you do not specify null precedence, then the exception goes away.

**Comment by mp911de** [comment] 2024-12-10 13:33
Closing as duplicate of #1280. Null precedence will come with Spring Data JPA 4.0.

**Closed by mp911de** 2024-12-10 13:33 UTC
Labels: status: duplicate
