### ISSUE TITLE
Already found parameter binding with same index / parameter name when using same parameter multiple times in native query

### ISSUE THREAD

**Issue by NaitYoussef** [spring-projects/spring-data-jpa#3154] opened 2023-09-12 09:37 UTC
The following Spring Boot Data test fails after migration 3.1.2 -> 3.1.3:
```
 	@Query(value = """
		SELECT c.car_id FROM car c		
		WHERE (coalesce(:collection) IS NULL OR c.car_id IN :collection)
		""", nativeQuery = true)
	Set<String> findCarsById(
			@Param("collection") Set<Long> sportIds,
	);
```	
with the following exception(I omitted the first lines of the stack trace):
```
Caused by: org.springframework.data.repository.query.QueryCreationException: Could not create query for public abstract java.util.Set com.car.repository.CarRepository.findCarsById(java.util.Set); Reason: Already found parameter binding with same index / parameter name but differing binding type; Already have: ParameterBinding [identifier: collection, origin: MethodInvocationArgument[identifier=collection]], found ParameterBinding [identifier: collection, origin: MethodInvocationArgument[identifier=collection]]; If you bind a parameter multiple times make sure they use the same binding
	at app//org.springframework.data.repository.query.QueryCreationException.create(QueryCreationException.java:101)
	at app//org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lookupQuery(QueryExecutorMethodInterceptor.java:115)
	at app//org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.mapMethodsToQuery(QueryExecutorMethodInterceptor.java:99)
	at app//org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lambda$new$0(QueryExecutorMethodInterceptor.java:88)
	at java.base@17.0.6/java.util.Optional.map(Optional.java:260)
	at app//org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.<init>(QueryExecutorMethodInterceptor.java:88)
	at app//org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:357)
	at app//org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:279)
	at app//org.springframework.data.util.Lazy.getNullable(Lazy.java:245)
	at app//org.springframework.data.util.Lazy.get(Lazy.java:114)
	at app//org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:285)
	at app//org.springframework.data.jpa.repository.support.JpaRepositoryFactoryBean.afterPropertiesSet(JpaRepositoryFactoryBean.java:132)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1817)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
	... 91 more
Caused by: java.lang.IllegalArgumentException: Already found parameter binding with same index / parameter name but differing binding type; Already have: ParameterBinding [identifier: collection, origin: MethodInvocationArgument[identifier=collection]], found ParameterBinding [identifier: collection, origin: MethodInvocationArgument[identifier=collection]]; If you bind a parameter multiple times make sure they use the same binding
	at org.springframework.util.Assert.isTrue(Assert.java:122)
	at org.springframework.data.jpa.repository.query.StringQuery$ParameterBindingParser.lambda$checkAndRegister$8(StringQuery.java:394)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.springframework.data.jpa.repository.query.StringQuery$ParameterBindingParser.checkAndRegister(StringQuery.java:394)
	at org.springframework.data.jpa.repository.query.StringQuery$ParameterBindingParser.lambda$parseParameterBindingsOfQueryIntoBindingsAndReturnCleanedQuery$0(StringQuery.java:242)
	at org.springframework.data.jpa.repository.query.StringQuery$ParameterBindings.register(StringQuery.java:501)
	at org.springframework.data.jpa.repository.query.StringQuery$ParameterBindingParser.parseParameterBindingsOfQueryIntoBindingsAndReturnCleanedQuery(StringQuery.java:318)
	at org.springframework.data.jpa.repository.query.StringQuery.<init>(StringQuery.java:85)
	at org.springframework.data.jpa.repository.query.DeclaredQuery.of(DeclaredQuery.java:40)
	at org.springframework.data.jpa.repository.query.JpaQueryMethod.assertParameterNamesInAnnotatedQuery(JpaQueryMethod.java:165)
	at org.springframework.data.jpa.repository.query.JpaQueryMethod.<init>(JpaQueryMethod.java:146)
	at org.springframework.data.jpa.repository.query.DefaultJpaQueryMethodFactory.build(DefaultJpaQueryMethodFactory.java:44)
	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$AbstractQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:94)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lookupQuery(QueryExecutorMethodInterceptor.java:111)
	... 103 more
```

After debug a little bit I found that the problem was the parameter "collection" has been added the first time to the binding list due to the first null check in the query but has a different type than the second binding added due to in clause. 

Since a binding has been added with the same name but has a different class the exception above is raised.

Is it normal that this query is not working anymore ?

Thank you for your help !

**Comment by mp911de** [comment] 2023-09-12 09:39
Duplicate of #3126

**Closed by mp911de** 2023-09-12 09:39 UTC
Labels: status: duplicate
