### ISSUE TITLE
version 2.7.8 native delete query cause NullPointerException

### ISSUE THREAD

**Issue by geewit** [spring-projects/spring-data-jpa#2813] opened 2023-02-22 03:15 UTC
version 2.7.8
@Transactional(rollbackFor = Exception.class)
    @Modifying(flushAutomatically = true, clearAutomatically = true)
    @Query(value = "delete u from sys_user u left join sys_org_user_rel rel on rel.user_id = u.user_id where rel.org_struct_id =:orgId and u.user_id = :userId", nativeQuery = true)
    void deleteByOrgIdAndId(@Param("orgId") long orgId, @Param("userId") long userId);
will cause NullPointerException during starting.
org.springframework.data.jpa.repository.query.QueryUtils.createCountQueryFor(QueryUtils.java:607)

but version 2.7.7 is ok.

**Comment by wstrzalka** [comment] 2023-02-22 11:22
I have the same - the issue seems to be introduced in this commit https://github.com/spring-projects/spring-data-jpa/commit/64b5a22a24b42e8660f441897b001e4b594fff1c
and the problematic statements is `variable.contains(",")` in this line https://github.com/spring-projects/spring-data-jpa/blob/25ed44c0046f70df302efc8af3e58377ad634735/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/query/QueryUtils.java#L620

**Comment by fiveOO** [comment] 2023-02-23 11:44
Same for me. 
Triggered by
```
@Query(value = "select NEXT VALUE FOR order_seq", nativeQuery = true)
BigInteger getNextOrderNo();
```
in an HSQLDB specific `JpaRepository`

**Comment by mp911de** [comment] 2023-02-23 12:49
Closing as duplicate of #2812

**Closed by mp911de** 2023-02-23 12:49 UTC
Labels: status: waiting-for-triage
