### ISSUE TITLE
java.lang.ClassNotFoundException: org.springframework.data.jpa.util.JpaMetamodelCacheCleanup

### ISSUE THREAD

**Issue by cmwarre** [spring-projects/spring-data-jpa#2444] opened 2022-02-18 00:59 UTC
I'm using spring-data-jpa without spring boot in an application and every time I try to startup my applications with repositories I'm getting the following exception:

`
org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [org.springframework.data.jpa.util.JpaMetamodelCacheCleanup] for bean with name 'org.springframework.data.jpa.util.JpaMetamodelCacheCleanup'; nested exception is java.lang.ClassNotFoundException: org.springframework.data.jpa.util.JpaMetamodelCacheCleanup
`

It looks to me like this class is currently Package-Private scoped so I wouldn't be able to initialize it?  Do I need to add an additional dependency or configuration?  

My project is currently using:

```
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-jpa</artifactId>
            <version>2.6.1</version>
        </dependency>
```

```
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>5.3.15</version>
        </dependency>
```

**Comment by schauder** [comment] 2022-02-18 07:28
Please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

**Comment by spring-projects-issues** [comment] 2022-02-25 07:30
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-03-04 07:30
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-03-04 07:30 UTC
Labels: status: waiting-for-feedback, status: feedback-reminder
