### ISSUE TITLE
 Already found parameter binding with same index / parameter name but differing binding type; 

### ISSUE THREAD

**Issue by miriyalajanardhan** [spring-projects/spring-data-jpa#3127] opened 2023-08-28 07:56 UTC
After upgrading to spring boot 3.1.3 getting the below error.

Below is the condition which is causing the error.   (List<String> regions
)
and ( :regions is null OR lower(c.region) IN (:regions) )

Caused by: java.lang.IllegalArgumentException: Already found parameter binding with same index / parameter name but differing binding type; Already have: ParameterBinding [identifier: regions, origin: MethodInvocationArgument[identifier=regions]], found ParameterBinding [identifier: regions, origin: MethodInvocationArgument[identifier=regions]]; If you bind a parameter multiple times make sure they use the same binding

Same code is working in spring boot 3.1.2

**Comment by miriyalajanardhan** [comment] 2023-08-30 07:33
Retried with 3.1.4-SNAPSHOT, still the issue is same.

**Comment by HengCC** [comment] 2023-09-01 11:00
same at https://github.com/spring-projects/spring-data-jpa/issues/3126#issuecomment-1702563890

**Comment by HengCC** [comment] 2023-09-04 01:29
@mp911de 
When I downgraded to version 3.0.9, there were no errors,

**Comment by gregturn** [comment] 2023-09-08 18:58
@HengCC Could you include a link to a reproducer, staged on github, ideally using https://start.spring.io, H2 (or Testcontainers for PostGreSQL, etc.), and the version of Spring Boot aligned with your issue?

Citing a single comment from another ticket isn't sufficient to hammer out this issue. 

It's quite natural that downgrading to an older version that didn't properly support re-used bindings might work, but it reintroduces an older problem we solved.

**Comment by HengCC** [comment] 2023-09-11 02:20
@gregturn Thanks for reply,   Downgrading can temporarily resolve the issue of the project not running. However, your point is valid; downgrading may reintroduce old problems. I have provided a temporary repository for reproducing this issue.

https://github.com/HengCC/jpa-param-index-demo.git

**Comment by mp911de** [comment] 2023-09-13 10:20
I'm not able to reproduce the issue anymore, hence closing this ticket.

**Closed by mp911de** 2023-09-13 10:20 UTC
Labels: status: duplicate, status: feedback-provided

**Comment by HengCC** [comment] 2023-09-13 10:31
@mp911de  Have you tried the example in the Git repository mentioned above? It can reproduce the issue. Below are the results I just ran.

<img width="1570" alt="image" src="https://github.com/spring-projects/spring-data-jpa/assets/6167532/45a7fb8f-8564-45be-9a02-998308838d1e">

**Comment by HengCC** [comment] 2023-09-13 10:51
@mp911de thanks ,  I think I've know the reason of this issue . It's still the same demo as above. With the current configuration, the issue no longer occurs
<img width="789" alt="image" src="https://github.com/spring-projects/spring-data-jpa/assets/6167532/6330c4e7-354d-4a0f-93f4-7f280e391bb0">
At the very beginning, spring-boot-starter-data-jpa:3.1.4-snapshot still depends on spring-data-jpa:3.1.3. 
Perhaps this is due to the IDE's cache or Maven's caching mechanism? Now that I've reverted the configuration, spring-boot-starter-data-jpa:3.1.4-snapshot now depends on spring-data-jpa:3.1.4-snapshot.  The issue can no longer be reproduced.

**Comment by mp911de** [comment] 2023-09-13 13:56
Spring Boot manages starter versions that do not necessarily map to Spring Data versions. Redeclaring either individual dependency versions, or better, specifying the Spring Data version property (`<spring-data-bom.version>2023.0.4-SNAPSHOT</spring-data-bom.version>`) is the way to override a dependency.
