### ISSUE TITLE
Sorting by function result not possible if function contains parameter and Sort.by is used  [DATAJPA-1750]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#2045] opened 2020-06-28 15:11 UTC
**[simonparadies](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER49520)** opened **[DATAJPA-1750](https://jira.spring.io/browse/DATAJPA-1750?redirect=false)** and commented

The FUNCTION_PATTERN regex in QueryUtils does not match functions containing positional or named parameters. Therefore, in these cases, the order by clause is constructed using the entities' qualifier, which leads to an incorrect expression

---

**Affects:** 2.4 M1 (2020.0.0)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-jpa/pull/425

**Comment by luitas** [comment] 2022-05-19 07:34
On 2.5.12 spring boot it works bu in 2.5.13 not working
In my case if i have 
```
pageable = PageRequest.of(pageable.getPageNumber(), pageable.getPageSize(), Sort.by(Sort.Direction.DESC, "inserted"));
return dataRecordRepository.findAllByFilter(pageable,1);

```
and in repository
```
@Query("select r From DataRecord r " +
            "  " +
            "where " +
                    " ( " +
            "       r.adusrId = :userId " +
            "       or EXISTS( select 1 FROM DataRecordDvsRight dr WHERE dr.adusrId = :userId AND dr.dataRecord = r ) " +
            ")")
    Page<DataRecord> findAllByFilter(Pageable pageable, @Param("userId") Long userId);
```
I get an error:
` Invalid path: 'dr.inserted' [select r From com.algoritmusistemos.media.app.entity.DataRecord r   where   (        r.adusrId = :userId        or EXISTS( select 1 FROM com.algoritmusistemos.media.app.entity.DataRecordDvsRight dr WHERE dr.adusrId = :userId AND dr.dataRecord = r ) ) order by dr.inserted desc]`

**Comment by schauder** [comment] 2022-05-19 08:30
Seems to be related to, possibly a duplicate of #2496

**Closed** 2022-05-19 20:24 UTC
Labels: type: bug, in: query-parser

**Comment by gregturn** [comment] 2022-05-19 20:31
Backported to `2.7.x` and `2.6.x`.
