### ISSUE TITLE
Switch to JPA 3.2 `Query.getSingleResultOrNull()`

### ISSUE THREAD

**Issue by david-kubecka** [spring-projects/spring-data-jpa#3701] opened 2024-12-03 13:01 UTC
I'm talking about this code: https://github.com/spring-projects/spring-data-jpa/blob/main/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/query/JpaQueryExecution.java#L224. As we know, `getSingleResult` throws an exception upon a non-existing entity. Since this is an allowed situation the exception is caught here https://github.com/spring-projects/spring-data-jpa/blob/main/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/query/JpaQueryExecution.java#L92.

I wonder why this try/catch approach (generally frowned upon) is used here instead of an alternative approach using `getResultList`, see e.g. https://stackoverflow.com/a/2885024/13015027. Apart from a slight performance penalty (not measured), the biggest problem of the current approach is that the exception is captured by telemetry agents (see https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/12125).

**Comment by mp911de** [comment] 2024-12-03 14:19
> the biggest problem of the current approach is that it pollutes the logs.

Care to elaborate? There should be no logging involved from our side. We could actually switch to `uniqueResultOptional`.

**Comment by david-kubecka** [comment] 2024-12-03 15:39
I've clarified the issue with a link (which I've found meanwhile) to an opentelemtry issue.

**Comment by mp911de** [comment] 2024-12-04 07:41
This ticket is a duplicate of #3633

**Comment by david-kubecka** [comment] 2024-12-04 10:39
Ok, the linked ticket has a much better description of the underlying OTEL problem.

Still, I would like to understand why it wouldn't be possible to replace the current `getSingleResult` call with an approach similar to the linked SO answer. AFAIK that one doesn't rely on anything Hbernate specific, utilizing plain JPA only.

**Comment by mp911de** [comment] 2024-12-09 10:31
We comply with the JPA spec by using `getSingleResult()`. If we now change (after using that functionality for almost 15 years) to a different strategy, I am pretty sure that we will break someone else's application because, in some particular cases, Hibernate (or Eclipselink) is doing things in `getSingleResult()` slightly differently than in `getResultList()`.

**Comment by david-kubecka** [comment] 2024-12-09 10:57
> We comply with the JPA spec by using getSingleResult().

Can you please point me to a guideline that mandates that you must use `getSingleResult` in this situation?

**Comment by david-kubecka** [comment] 2024-12-09 11:47
Yes, I read that doc snippets. And I see nothing in them that would indicate that using getResultList in your case is wrong or unsafe (assuming, of course, that providers implement the specification correctly).

Anyway, looks like `getSingleResultOrNull` could be available soon so if you are willing to use that then perhaps you can do that under this ticket (I can add getSingleResultOrNull as another option to the description).

**Comment by mp911de** [comment] 2024-12-09 13:12
Alright, I repurposed this ticket and marked it for inclusion for our `4.0.x` branch.

**Closed** 2024-12-20 10:02 UTC
Labels: type: enhancement
